### ISSUE TITLE
Atlassian Crowd authenticator

### ISSUE THREAD

**Issue by cornelf** [cesanta/docker_auth#100]
Authentication through a Generic Crowd application on a Crowd Server would be really cool to have.
I kindly challenge
- @3rf based on https://github.com/evergreen-ci/crowd
- @jda based on https://github.com/jda/go-crowd
  
  to give it a go 😏

**Comment by rojer** [comment]
i'm going to close this - if needed, you can now implement it as an external program via [ext_auth](https://github.com/cesanta/docker_auth/blob/b5b63d933e370be6abdd0b4744af1279159a69ea/examples/reference.yml#L133).
