### ISSUE TITLE
Allow terminate TLS on ngnix or apache and proxy to docker_auth

### ISSUE THREAD

**Issue by jay1xiong** [cesanta/docker_auth#101]
It is desirable to terminate TLS on nginx or apache server rather terminate TLS on docker_auth directly. This deployment is similar to TLS termination for docker-registry using ngnix or apache front end.

**Comment by rojer** [comment]
in this case generating a cert/key pair for use between proxy and the auth server should suffice.
as mentioned in #102, it doesn't have to be the same as the one used for signing tokens.
is there a reason why this won't work?

**Comment by jay1xiong** [comment]
It should work. But it does not make a lot of sense to do another TLS internally between proxy and auth server. You have to generate another private key/certificate pair without much benefit as the communication is internal.

**Comment by rojer** [comment]
initially SSL/TLS was mandatory for http server, but since e946750e82b253a56c46a676b20ae8ca268d9b53 it no longer is, so you should be able to run the server without `server.certificate` and `server.key`.

**Comment by jay1xiong** [comment]
Thanks for the pointer. I am using docker_auth container. Neither docker_auth.stable nor docker_auth.latest work without certificate/key configuration. They are both marked as CREATED 10 weeks ago. Do I need to build my own?

**Comment by carsonoid** [comment]
You probably just need to explicitly pull them again. `docker pull
cesanta/docker_auth:latest` Since the tag hasn't change you need to force
docker to pull the latest image.

**Comment by rojer** [comment]
remember also that you must set `token.certificate` and key in this case.
i just tried and it works as expected. you should see
```
W0607 11:48:20.735234   32089 main.go:78] Running without TLS
```
in the log.

**Comment by jay1xiong** [comment]
It all works! :-)

Thanks
