### ISSUE TITLE
Use separate private key/certificate pair for TLS and JWT token

### ISSUE THREAD

**Issue by jay1xiong** [cesanta/docker_auth#102]
The current implementation combines the usage of private key/certificate for TLS and JWT token. For improved security, they should not share the same private key/certificate. The private key/certificate for TLS generally generated from trusted CA.

**Comment by rojer** [comment]
it is possible to specify a different issue certificate for tokens by specifying `token.certificate` and `token.key`, as documented [here](https://github.com/cesanta/docker_auth/blob/master/examples/reference.yml#L26).

**Comment by jay1xiong** [comment]
Can you add the same comment to ldap_auth.yml as well? I was only looking at the file since I only need to support ldap authentication.

**Comment by rojer** [comment]
done
