### ISSUE TITLE
How to use mongo auth

### ISSUE THREAD

**Issue by KaleoCheng** [cesanta/docker_auth#109]
Hi，If this is a  stupid question, forgive me.
Could you add something about how to use mongo auth in the README? The following is my acl:

```shell
{ "_id" : ObjectId("5773b1755dc23cb6e6df6960"), "test" : { "password" : "$2y$05$LO.vzwpWC5LZGqThvEfznu8qhb5SGqvBSWY1J3yZ4AxtMRZ3kN5jC" } }
```
It doesn't seem to work. Is not correct?

**Comment by houht** [comment]
You can refer to  master/docs/Backend_MongoDB.md.
My tests are as follows,mongo port should be accessed：

conf:
mongo_auth:
  dial_info:
    addrs: ["10.0.2.47:27017"]
    timeout: "10s"
    database: "docker_auth"
    user: ""
    password_file: ""
  collection: "users"

mongo:
1 use docker_auth
2 db.createCollection("users")
3 db.users.save({username:'admin',password:'$2y$05$LO.vzwpWC5LZGqThvEfznu8qhb5SGqvBSWY1J3yZ4AxtMRZ3kN5jC'})

**Comment by KaleoCheng** [comment]
@houht Oh,Thanks~
