### ISSUE TITLE
docker run with ldap is successful, what's the next step?

### ISSUE THREAD

**Issue by SydOps** [cesanta/docker_auth#111]
I have run the command with ldap setting, should be correct. 

The docker container is running with port 5001 open. 

```
1854a7c93862        cesanta/docker_auth:stable   "/auth_server --v=2 -"   4 seconds ago       Up 2 seconds             0.0.0.0:5001->5001/tcp             docker_auth
```

What's the next step? How can I link it to docker registry v2? Any instructions?

```
I0710 10:26:01.780239       1 server.go:2161] http: TLS handshake error from 172.17.0.1:36514: tls: first record does not look like a TLS handshake
I0710 10:26:26.515645       1 server.go:2161] http: TLS handshake error from 172.17.0.1:36516: EOF
```

**Comment by SydOps** [comment]
Got the help from https://github.com/kwk/docker-registry-setup

That's nice to get explained with a useful [docker-compose.yml](https://github.com/kwk/docker-registry-setup/blob/master/docker-compose.yml) file

**Comment by SydOps** [comment]
Here is the setting I need follow.

https://github.com/kwk/docker-registry-setup/blob/master/registry/conf/config.yml#L22

**Comment by houht** [comment]
https://github.com/docker/distribution/blob/master/docs/spec/auth/token.md
