### ISSUE TITLE
how to use http protocol between docker and docker_auth?

### ISSUE THREAD

**Issue by duyanghao** [cesanta/docker_auth#116]
I want to use nginx as Load balancing of auth_server, and i want to use http protocol between nginx and auth_server,
i change the configuration on the side of registry v2 below:
```
#  auth:
#    token:
#      realm: "http://127.0.0.1:5001/auth"
#      service: "Docker registry"
#      issuer: "Acme auth server"
#      rootcertbundle: "/path/to/server.pem"
```
i use `http://127.0.0.1:5001/auth` instead of `https://127.0.0.1:5001/auth`,but the error appears on the side of auth_server below:
`tls: first record does not look like a TLS handshake`

**Comment by rojer** [comment]
you need to disable TLS on the auth server side to. remove server.certificate and server.key and move them to token.certificate and token.key

**Comment by duyanghao** [comment]
you means,the configuration on the side of auth_server like below:

```

server:  # Server settings.
  # Address to listen on.
  addr: ":5001"


token:  # Settings for the tokens.
  issuer: "Acme auth server"  # Must match issuer in the Registry config.
  expiration: 900
  # It is possible configure a different certificate for tokens.
  # If not specified, server certificate is used.
  certificate: "..."
  key: "..."
```
Is that right?

**Comment by rojer** [comment]
yes

**Comment by duyanghao** [comment]
another question:
```
token:  # Settings for the tokens.
  issuer: "Acme auth server"  # Must match issuer in the Registry config.
  expiration: 900
  # It is possible configure a different certificate for tokens.
  # If not specified, server certificate is used.
  # certificate: "..."
  # key: "..."

```
Is the expiration refers to expires_in in Registry token document?
https://github.com/docker/distribution/blob/master/docs/spec/auth/token.md

```
expires_in
(Optional) The duration in seconds since the token was issued that it will remain valid. When omitted, this defaults to 60 seconds. For compatibility with older clients, a token should never be returned with less than 60 seconds to live.
```

**Comment by rojer** [comment]
yes, correct
