### ISSUE TITLE
Error response from daemon "crypto/rsa: verification error" while accessing registry using auth and tls

### ISSUE THREAD

**Issue by ashishjain14** [cesanta/docker_auth#128]
Steps to reproduce the issue:
1. Set up a secure docker registry with auth & tls
2. Set up cessanta docker auth server
3. Do Not set --insecure-registry option in DOCKER_OPTS
4. docker push or pull fails with the following error
Error response from daemon: Get https://xxxxxxxxxxxx:5000/v2/: Get https://xxxxxxxxxxx:5001/auth?account=admin&client_id=docker&offline_token=true&service=Docker+registry: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "xxxxxxxxxxx")
5. If I set up --insecure-registry it works without any issues

**Comment by ashishjain14** [comment]
Further debugging suggests there is trust deficit between auth-server and docker client. I see the following error in docker-auth server

I0814 13:16:26.354676       1 server.go:2161] http: TLS handshake error from xxxxxxxxxxxxx:58132: remote error: bad certificate
I0814 13:16:31.358064       1 server.go:2161] http: TLS handshake error from xxxxxxxxxxxxx:58133: remote error: bad certificate

I use the following command to create the certificate
sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout server.key -out server.pem

I have copied the server.pem as server.crt in /usr/local/share/ca-certificates. But looks like this is not sufficient.

One point to note here is that challenge with auth_server works differently with --insecure-registry enabled and I do not see the above issue.

**Comment by rojer** [comment]
i can't help you with cert trust issues. use `openssl s_client` to debug or something.
sorry, this is just out of scope of auth_server and i'm not paid to provide generic support.

**Comment by ashishjain14** [comment]
Currently I have a workaround here by using a plain http docker auth_server but there is definitely an issue which looks like is at the docker end. with openssl s_client I am able to establish connection with auth server so this definitely seems to be a docker issue.
