### ISSUE TITLE
auth-server with docker-notary fails with error HTTP 400 response body: invalid character 'B'

### ISSUE THREAD

**Issue by ashishjain14** [cesanta/docker_auth#129]
I have been able to successfully use auth-server with docker registry. Trying to use the same with docker notary and I am seeing following error

RRO[0000] Could not publish Repository since we could not update: error parsing HTTP 400 response body: invalid character 'B' looking for beginning of value: "Bad request: invalid scope: \"repository:xxxxxxxxxxxx:5000/golang:push,pull\"\n"
Failed to sign "xxxxxxxxxxxx:5000/golang":test - error parsing HTTP 400 response body: invalid character 'B' looking for beginning of value: "Bad request: invalid scope: \"repository:xxxxxxxxxx:5000/golang:push,pull\"\n"
error parsing HTTP 400 response body: invalid character 'B' looking for beginning of value: "Bad request: invalid scope: \"repository:xxxxxxxxxxxx:5000/golang:push,pull\"\n"

This happens once I import the auth-server certificate at my docker client end. This is done to establish a trust between auth-server and my docker client host.

**Comment by rojer** [comment]
wait, this doesn't make sense to me.
where are these logs from?

**Comment by ashishjain14** [comment]
This I suppose is coming from https://github.com/cesanta/docker_auth/blob/f78c304094a6679b524251d4d587bc3a24fcb4d9/auth_server/server/server.go#L172

**Comment by ashishjain14** [comment]
One more point to add here I run the following command
docker push xxxxxxxxxx:5000/golang:test
so there is a tag "test" also at the end 

But above in the error message I see golang:push,pull

**Comment by ashishjain14** [comment]
Comment from docker team
https://github.com/docker/notary/issues/916#issuecomment-239861223

**Comment by rojer** [comment]
thank you! this should be easy to fix, please try `:latest`.

**Comment by ashishjain14** [comment]
I still have the same issue, with latest

**Comment by rojer** [comment]
strange, works for me. please make sure you re-pulled `:latest` and if it still doesn't work, please post full auth_server log at `--v=2`.

**Comment by ashishjain14** [comment]
Not sure if I understood you correctly, do you mean I should run
docker push xxxxxxxxxx:5000/golang:latest

**Comment by ashishjain14** [comment]
I just pulled latest docker_auth image and looks like it worked. I will run few more tests over few days and provide more updates on this issue. Thanks a lot for your prompt response.

**Comment by rojer** [comment]
i meant pull `docker_auth:latest` with the fix. looks like you did it and it works, ok.

**Comment by ashishjain14** [comment]
The previous one which worked was when I used a http connection. Now switching http connection to https is making it fail again which I have pointed out earlier at you. Just wanted to check with you that was your docker_auth server listening on http or https.

**Comment by rojer** [comment]
http/https is probably the trust issue you described, which cannot possibly be related to this.

**Comment by ashishjain14** [comment]
agreed your fix works and this is unrelated to current issue. Just checking if you guys have been able to make https work with docker. Have raised an issue with docker here https://github.com/docker/docker/issues/25682

**Comment by rojer** [comment]
yes, for example `docker.cesanta.com` uses SSL

**Comment by ashishjain14** [comment]
okay thanks for this information, appreciate your help and prompt reply
