### ISSUE TITLE
Add Support for Github Enterprise

### ISSUE THREAD

**Issue by spkane** [cesanta/docker_auth#135]
Some organizations, run GitHub Enterprise, which is simply an internal version of Github. In general, supporting this should be a simple matter, of allowing the base Github URL to be changed.

I'd be happy to test any implementations out if someone wants to take on writing it.

**Comment by rojer** [comment]
yes, this should be easy enough.
so, in GH enterprise, what is the OAuth URL? i.e. this thing here: https://github.com/cesanta/docker_auth/blob/a6b51a80da2dc15b2a52647d69b45b70c9ca0b1e/auth_server/authn/github_auth.go#L99
and what is the API URL (`api.github.com`)? are they separately configurable?

**Comment by spkane** [comment]
So, I believe that ```https://api.github.com/``` would become ```https://ghe.example.com/api/v3/```

and I think auth should be done against this API endpoint:

https://ghe.example.com/api/v3/authorizations/clients/

These docs should cover it:

https://developer.github.com/enterprise/2.3/v3/oauth_authorizations/#oauth-authorizations-api

**Comment by rojer** [comment]
hm. authorizations is not exactly the thing, as far as i understand. it is described as an alternative to web flow, but we do implement web flow.
anyway, i put together this small change - https://github.com/cesanta/docker_auth/compare/gh?expand=1

try `cesanta/docker_auth:test135`, set `github_auth.ghe_host` and see if it works

**Comment by rojer** [comment]
@spkane have you had a chance to try it?

**Comment by spkane** [comment]
Sorry, I have not yet. Priorities just shifted a bit recently, but this is still something we want to do. I'll make a note to dive into this when I have some extra time in the next week or 2, and then give you some feedback. Thanks!

**Comment by rojer** [comment]
i am going to close this on the assumption that #151 fixes it.
feel free to reopen if not.
