### ISSUE TITLE
Allow tag limits in ACL

### ISSUE THREAD

**Issue by rmoriz** [cesanta/docker_auth#136]
Let's say we have the following situation:

```
docker.registry/namespace/image:latest
docker.registry/namespace/image:beta3
```

Some users should be able to access the image tagged as "beta3" but others must not.

I've tried the following without success:

```yaml
  - match: {account: "customer123", name: 'namespace/image:beta3' }
    actions: ["pull"]
```

=> ` {customer123 pull repository namespace/image} did not match any authz rule`

**Comment by rojer** [comment]
would be great, but unfortunately it's not feasible - token request simply does not include the tag, only repository name. you should bring that up with docker devs.
