### ISSUE TITLE
Token auth is generated, but registry responds 403 Forbidden

### ISSUE THREAD

**Issue by summerQLin** [cesanta/docker_auth#14]
Hi, @rojer , since last week I succeeded with auth by account test:test by fixing certs issues. Today I tried again, I got another error. 

Without any credential saved in my local, I tried docker push localhost:5000/test-busybox:latest.
<pre><code>8c2e06607696: Image push failed
FATA[0000] Error pushing to registry: token auth attempt for registry http://localhost:5000/v2/: https://127.0.0.1:5001/auth?scope=repository%3Atest-busybox%3Apull%2Cpush&service=Docker+registry request failed with status: 403 Forbidden</code></pre>

I expect the commandline will ask me username and password, as I've seen last week.

By the way, if I try   docker login localhost:5000, input username test, password test, I was able to login.

If I try to curl 
<pre><code>curl -k -u test:test https://127.0.0.1:5001/auth?scope=repository:test-busybox:push&service=Docker+registry</code></pre>
It gave me the token
<pre><code> {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlZJU006NFhOSjpCQUdMOkUyVFU6S0VQVzpIVDNTOkYzT0U6UkxLTzpUSlA0OkVTTDU6WUVUMzpUUEFLIn0.eyJpc3MiOiJBY21lIGF1dGggc2VydmVyIiwic3ViIjoidGVzdCIsImF1ZCI6IiIsImV4cCI6MTQzMzkzMzA2MCwibmJmIjoxNDMzOTMyMTU5LCJpYXQiOjE0MzM5MzIxNjAsImp0aSI6IjQ2MDc3MzAzODg0ODkxMDM0NjIiLCJhY2Nlc3MiOlt7InR5cGUiOiJyZXBvc2l0b3J5IiwibmFtZSI6InRlc3QtYnVzeWJveCIsImFjdGlvbnMiOlsicHVzaCJdfV19.o-fFYibAPBGnWC2B8NIKyMZdZIT4KFFWRfEYhSszk_HvJfURLDfOUahRV30fgsjudza0rCpo7jYwnAeyz3qcVM3wMTlxdK5nZ_qC7AVqoAj7lIZZNfGpGjFBbzB0VA60dt8zVxY3fF1H-wl1sk0ml_keAOz4r9x2mTIe89RZGSwsd1vcGSYbRJbzz7fG3hSGX18ekVuxgJ9MaOAsbEvNakn20UBhobTyL8OZVczaQEH4dr3x0nH9Zfz_GI1I6C5oMdUw4tWdEB3aqMP3ALVYeg8d_cLJ5a2aLh00O9RFS-6GwLQtUI4uoI2hJ3gcRH87b4yxaf26pFKE1bCcRQYrug"}</code></pre>
Seems auth server is working. But why registry gave me 403 even without asking me for username and password???
And here is registry's log, the wired thing is it reports 401 instead of 403???
<pre><code>time="2015-06-10T10:33:01.89432815Z" level=debug msg="authorizing request" environment=development http.request.host="localhost:5000" http.request.id=57dfc29a-0ec3-4ffb-b1cb-1aeed52d04e1 http.request.method=GET http.request.remoteaddr="172.17.42.1:37871" http.request.uri="/v2/" http.request.useragent="docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-48-generic os/linux arch/amd64" instance.id=9ab8120f-fb74-4b3f-a062-324bc6760508 service=registry version=v2.0.0-179-g3073b1d.m
time="2015-06-10T10:33:01.895085187Z" level=error msg="error authorizing context: authorization token required" environment=development http.request.host="localhost:5000" http.request.id=57dfc29a-0ec3-4ffb-b1cb-1aeed52d04e1 http.request.method=GET http.request.remoteaddr="172.17.42.1:37871" http.request.uri="/v2/" http.request.useragent="docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-48-generic os/linux arch/amd64" instance.id=9ab8120f-fb74-4b3f-a062-324bc6760508 service=registry version=v2.0.0-179-g3073b1d.m
time="2015-06-10T10:33:01.895478806Z" level=info msg="response completed" environment=development http.request.host="localhost:5000" http.request.id=57dfc29a-0ec3-4ffb-b1cb-1aeed52d04e1 http.request.method=GET http.request.remoteaddr="172.17.42.1:37871" http.request.uri="/v2/" http.request.useragent="docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-48-generic os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=6.673508ms http.response.status=401 http.response.written=114 instance.id=9ab8120f-fb74-4b3f-a062-324bc6760508 service=registry version=v2.0.0-179-g3073b1d.m
172.17.42.1 - - [10/Jun/2015:10:33:01 +0000] "GET /v2/ HTTP/1.1" 401 114 "" "docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-48-generic os/linux arch/amd64"
time="2015-06-10T10:33:01.905632772Z" level=debug msg="authorizing request" environment=development http.request.host="localhost:5000" http.request.id=7b4585d7-5546-4bc7-8897-259b9cee2a35 http.request.method=GET http.request.remoteaddr="172.17.42.1:37877" http.request.uri="/v2/" http.request.useragent="docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-48-generic os/linux arch/amd64" instance.id=9ab8120f-fb74-4b3f-a062-324bc6760508 service=registry version=v2.0.0-179-g3073b1d.m
time="2015-06-10T10:33:01.906005775Z" level=error msg="error authorizing context: authorization token required" environment=development http.request.host="localhost:5000" http.request.id=7b4585d7-5546-4bc7-8897-259b9cee2a35 http.request.method=GET http.request.remoteaddr="172.17.42.1:37877" http.request.uri="/v2/" http.request.useragent="docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-48-generic os/linux arch/amd64" instance.id=9ab8120f-fb74-4b3f-a062-324bc6760508 service=registry version=v2.0.0-179-g3073b1d.m
time="2015-06-10T10:33:01.906345031Z" level=info msg="response completed" environment=development http.request.host="localhost:5000" http.request.id=7b4585d7-5546-4bc7-8897-259b9cee2a35 http.request.method=GET http.request.remoteaddr="172.17.42.1:37877" http.request.uri="/v2/" http.request.useragent="docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-48-generic os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=4.724482ms http.response.status=401 http.response.written=114 instance.id=9ab8120f-fb74-4b3f-a062-324bc6760508 service=registry version=v2.0.0-179-g3073b1d.m
172.17.42.1 - - [10/Jun/2015:10:33:01 +0000] "GET /v2/ HTTP/1.1" 401 114 "" "docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-48-generic os/linux arch/amd64"</code></pre>

**Comment by rojer** [comment]
please enable verbose output by passing these argument to the auth server (before config file name): --logtostderr --v=2

it should be clear why request was denied, or post output here and i'll take a look

**Comment by summerQLin** [comment]
Here is log from docker_auth
<pre><code>
I0610 14:55:06.450693       1 server.go:166] Request: &{Method:GET URL:/auth?scope=repository%3Atest-busybox%3Apull%2Cpush&service=Docker+registry Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[User-Agent:[docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-48-generic os/linux arch/amd64] Accept-Encoding:[gzip]] Body:0x93b0e0 ContentLength:0 TransferEncoding:[] Close:false Host:127.0.0.1:5001 Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:172.17.42.1:59513 RequestURI:/auth?scope=repository%3Atest-busybox%3Apull%2Cpush&service=Docker+registry TLS:0xc2080b6580}
W0610 14:55:06.451203       1 server.go:110] {:@172.17.42.1:59513  pull,push repository test-busybox} did not match any rule</code></pre>

My configuration:
<pre><code>acl:
  # Admin has full access to everything.
  - match: {account: "admin"}
    actions: ["*"]
  # User "test" has full access to test-* images but nothing else.
  - match: {account: "test", name: "test-*"}
    actions: ["*"]
  - match: {account: "test"}
    actions: []
  # All logged in users can pull all images.
  - match: {account: "/.+/"}
    actions: ["pull"]
  # Anonymous users can pull "hello-world".
  - match: {account: "", name: "hello-world"}
    actions: ["pull"]</code></pre>
 
I don't very understand why it doesn't match rule. Thank you for looking at my issue.

**Comment by rojer** [comment]
note that username and password are empty: {:@172.17.42.1:59513 ...}

it should be test:***@172.17.42.1:59513 (passwords are screened, will appear as asterisks in the log).
hm. can you add -v to your curl command and post output here? (it will have all the headers that are sent)

**Comment by rojer** [comment]
ah sorry, so curl doe work.
well, then it just means that you need to run docker login

**Comment by rojer** [comment]
"docker login your_registry:5000"

**Comment by summerQLin** [comment]
Yes, I got it pushed. But shouldn't registry ask for username and password if credential is not saved, instead error message?

**Comment by rojer** [comment]
it might be nice, but you'll need to raise that with docker devs.

**Comment by summerQLin** [comment]
Thank you very much. I guess that functionality is from registry v1?

**Comment by rojer** [comment]
hm, it does? maybe that's a difference between 401 and 403 responses. i need to test it.

**Comment by summerQLin** [comment]
I am testing Docker hub enterprise, it include an auth server. If you push without login, it says
<pre><code>FATA[0000] Error pushing to registry: token auth attempt for registry http://localhost:80/v2/: https://127.0.0.1/auth/token?scope=repository%3Abusybox%3Apull%2Cpush&service=127.0.0.1 request failed with status: 401 Unauthorized</code></pre>
And  it doesn't ask for username and password.

I saw that username and password  prompt using nginx proxy server to authenticate user.

**Comment by rojer** [comment]
well, then there you go. looks like in case of token authentication docker client doesn't ask for password.
i think it's reasonable to request that it should, but that would be docker feature request.
one thing i will change is to return 401 for both authentication and authorization failures.

**Comment by rojer** [comment]
https://github.com/cesanta/docker_auth/commit/893d12db6492f3d9a96b9f778a1ab3659cd83fbb

i don't think there's anything else i can do here.

**Comment by tyagian** [comment]
There is temporary solution working fine for me:
Just change config.jason file to 

{
"auths": {
"https://index.docker.io/v1/": {
"auth": "<hash value>",
"email": "<email-d>"
},
"https://registry-win-tp3.docker.io/v1/": {
"auth": "<hash value>",
"email": "<email-address>"
}
}
}

<a href="
http://networkengg.com/docker-login-failed-on-windows-403-forbidden-error/">Docker 403 forbidden error</a>
