### ISSUE TITLE
Deploying in HA mode

### ISSUE THREAD

**Issue by cpdevws** [cesanta/docker_auth#145]
Is it possible to bring up docker_auth service in HA mode (i.e. starting docker_auth container on two separate VMs behind a reverse proxy or load balancer)?

Has anyone tried this or have some insights into this, please share? I am worried, that the JWT tokens issued by the docker_auth service will not be the same across multiple instances (for the same user). Please validate my understanding.

**Comment by rojer** [comment]
tickets won't be exactly the same in any case.
what matters is that the behavior of the instances is the same - i.e. that they all authorize the same actions by the same users.
if you use static authn/authz or authn/authz backed by the same backend, it should be fine (though e.g. in case of mongo acls there may be a period after acl change where some instances have not reloaded the acls yet and some have).
notably, where multiple instances will not work, is if you use github or google auth - those use local token storage and thus authenticating on one will not authenticate you on the rest of the instances. issue #126 is about that.

**Comment by carsonoid** [comment]
I successfully use multiple (3-5) instances of auth_server with Mongo for a ACLs and users. Works like a charm.

**Comment by rojer** [comment]
thanks, @carsonoid 

i'm going to close this, hope the question has been answered.
