### ISSUE TITLE
Empty scope is not handled

### ISSUE THREAD

**Issue by gbougeard** [cesanta/docker_auth#146]
I'm using https://github.com/heroku/docker-registry-client to interact with my registry.
When getting /v2/ the challenge returned does not contain a scope  (seems legit). 
But the heroku lib specify `scope` even if it's empty : `GET /auth?scope=&service=Docker+registry` .

This is not well handled on docker-auth side : `Bad request: invalid scope: ""` .

According the spec https://docs.docker.com/registry/spec/auth/token/#/requesting-a-token , the scope might be empty.

**Comment by rojer** [comment]
should've been fixed, thank you!

**Comment by gbougeard** [comment]
thx to you @rojer When the `latest` image should be updated and available?

**Comment by rojer** [comment]
just pushed, in `:latest` now

**Comment by gbougeard** [comment]
Thx. I confirm, it's fixed.
