### ISSUE TITLE
Question about compiling

### ISSUE THREAD

**Issue by xiekeyang** [cesanta/docker_auth#15]
Dear @rojer 
Dockerfile is under auth_server folder.
So , `ADD auth_server /` in Dockerfile  seems to lead compiling failed.
compiling is OK when i move dockerfile to upper folder.
However, container running will be failed:
**run command**
```bash
$sudo docker run \
   --rm -it --name docker_auth -p 5001:5001 \
   -v /go/src/github.com/cesanta/docker_auth/auth_server/config:/config:ro \
   -v /var/log/docker_auth:/logs \
   -v /go/src/github.com/cesanta/docker_auth/auth_server/certs:/path/to/certs:ro \
   cesanta/docker_auth /config/auth_config.yml
```

**error**:
```bash
exec: "/auth_server": permission denied
FATA[0000] Error response from daemon: Cannot start container 9eb651d5c27dc32116a5ae06900e56dac54acfe0d82197ea4026ff3c745b0a3e: [8] System error: exec: "/auth_server": permission denied 
```

same running is OK when i use image cesanta/docker_auth on Docker Hub.
If I made mistake?

**Comment by rojer** [comment]
auth_server is a directory, so if you build with context at the top level it will add the whole auth_server directory and executing that will fail.
the right way to build it (well, the way i do it anyway) is to run make within the auth_server directory.
