### ISSUE TITLE
GitHub auth is broken in latest release

### ISSUE THREAD

**Issue by KDFischer** [cesanta/docker_auth#169]
Dear Cesanta Docker-Auth team,

I think the Github authentication in the latest version (1.2) is broken. I never programmed in GO, but I think the problem is that function doGitHubAuthPage doesn't parse GithubWebUri to fill in the URL in the template. Version 1.1, which has the uri hardcoded in the template, is working.

Thanks for this great tool!

Cheers,
Kasper

**Comment by bramswenson** [comment]
Agreed. There is button rendered on the page at `/github_auth` that indicates a template error. Here is the source:
```
<button type="button" onclick="location.href='Template error: template: github_auth:3:50: executing " github_auth"="" at="" <.githubweburi="">: GithubWebUri is not a field of struct type struct { ClientId string }
</button>
```
I've even tried hardcoding the `github_web_uri` config value to what is clearly the defaults. No joy.
