### ISSUE TITLE
The docker image cannot be started

### ISSUE THREAD

**Issue by murphyleung** [cesanta/docker_auth#17]
we are having problem to started and we have no idea how to resolve it:

[root@docker-registry tmp]# docker run --rm -it --name docker_auth -p 5001:5001     -v /tmp/:/config:ro     -v /var/log/docker_auth:/logs     cesanta/docker_auth --v=2 /config/docker_auth.yml
F0714 08:29:46.246461       1 main.go:146] Failed to load config: could not read /config/docker_auth.yml: open /config/docker_auth.yml: permission denied

we got "permission denied" error on reading the yml file but this is already set to 777.

**Comment by rojer** [comment]
sorry, can't be of much help here... permission denied is permission denied, why your system denies reading /tmp/docker_auth.yml i have no idea.
