### ISSUE TITLE
Different docker baseimage than busybox?

### ISSUE THREAD

**Issue by muralikg** [cesanta/docker_auth#171]
Extending `busybox` based docker image is difficult can you please update it to `alpine` which also has a small footprint but much more easy to extend.

Extending the image becomes necessary when using ext_auth

**Comment by fentas** [comment]
I currently use this repo to extend `docker_auth`. But I would like to get rid of it.
https://github.com/progrium/busybox

**Comment by mgenov** [comment]
This is what we are using for our Go stuff: 

```docker
FROM alpine:3.4

RUN apk add --no-cache ca-certificates apache2-utils

WORKDIR /app
ENTRYPOINT ["/app/myapp"]
```

The image is small enough and doesn't require ca-certifcates to be copied from the local filesystem.

**Comment by everett-toews** [comment]
Thanks for sharing @mgenov. We're doing something similar but I used a multi-stage build to keep the image as small as possible. And then added in some utils we need much like you did.

```yaml
FROM golang:1.8-alpine as build

RUN apk --no-cache add git
RUN go get -v -u -f github.com/tools/godep github.com/jteeuwen/go-bindata/...

COPY . /go/src/github.com/cesanta/docker_auth/auth_server
WORKDIR /go/src/github.com/cesanta/docker_auth/auth_server

RUN go get -v -d .
RUN go install -v .


FROM alpine:latest

RUN apk --no-cache add curl jq

COPY --from=build /go/bin/auth_server .

EXPOSE 5001

ENTRYPOINT ["./auth_server"]
CMD ["/config/auth_config.yml"]
```

**Comment by rojer** [comment]
oh wow, i wasn't even aware that such multistage process is possible.
thanks for sharing, @everett-toews

**Comment by fentas** [comment]
@everett-toews thanks a lot. I could not build it from source. Got an error:
```
Step 9/21 : RUN go install -v .
 ---> Running in 16c2486b9831
golang.org/x/net/context
github.com/golang/protobuf/proto
golang.org/x/net/http2/hpack
golang.org/x/text/transform
...
github.com/cesanta/docker_auth/auth_server/server
gopkg.in/fsnotify.v1
github.com/cesanta/docker_auth/auth_server
# github.com/cesanta/docker_auth/auth_server
./main.go:174: undefined: Version
./main.go:174: undefined: BuildId
```

But I ended up just doing this:
```
FROM cesanta/docker_auth:1.3 as build

FROM alpine:3.6
COPY --from=build /docker_auth /docker_auth
# doing my stuff...
RUN apk add --no-cache curl jq openssl
```
Real simple that way. :+1:

**Comment by muralikg** [comment]
Thanks @everett-toews  and @fentas , the solution provided allows us to use it with any base image of our choice.
Will be closing this as there is no need to change current busybox based image.
