### ISSUE TITLE
GitHub auth does not work

### ISSUE THREAD

**Issue by franfran3** [cesanta/docker_auth#172]
After configuring github auth only, getting on the main auth page displays the source code. The Content-Type header is invalid (`text-html` instead of `text/html`) as shown in auth_server/server/server.go +352.

Once fixed, the /github_auth URL shows a button 
```html
<button type="button" onclick="location.href='Template error: template: github_auth:3:50: executing " github_auth"="" at="" <.githubweburi="">: GithubWebUri is not a field of struct type struct { ClientId string }
</button>
```

**Comment by rojer** [comment]
template rendering error was fixed in #169
