### ISSUE TITLE
Latest change has broken docker image

### ISSUE THREAD

**Issue by tboerger** [cesanta/docker_auth#173]
The latest change has broken the docker image, it fails to start with:

```
standard_init_linux.go:178: exec user process caused "no such file or directory"
```

If I get into the container with `sh`, change to `/docker_auth` and execute `./auth_server` I get `sh: ./auth_server: not found`.

I am using `cesanta/docker_auth:1`.

**Comment by tboerger** [comment]
I have switched to `1.2` for now as it still works.

**Comment by rojer** [comment]
sorry about that, rebuilt and repushed the relevant images

**Comment by tboerger** [comment]
Thank you for the fast reaction.
