### ISSUE TITLE
Support multiple LDAP (fallback)

### ISSUE THREAD

**Issue by alonbl** [cesanta/docker_auth#179]
Hi,
Currently a single LDAP server can be provided.
It would be nice if multiple addresses can be provided so that a fallback can be achieved.
Most applications support this simple fallback sequence to reduce downtime.
Thanks!

**Comment by rojer** [comment]
the library we use (https://github.com/go-ldap/ldap) does not support specifying more than one server.
given that, i do not think that developing failover functionality is in scope for this project.
i suggest you deploy a failover proxy/load balancer to provide fault tolerance.
