### ISSUE TITLE
Support URL prefix

### ISSUE THREAD

**Issue by alonbl** [cesanta/docker_auth#181]
Hi,

Current URLs are hardcoded, as in:
```
        case req.URL.Path == "/":
                as.doIndex(rw, req)
        case req.URL.Path == "/auth":
                as.doAuth(rw, req)
        case req.URL.Path == "/google_auth" && as.ga != nil:
                as.ga.DoGoogleAuth(rw, req)
        case req.URL.Path == "/github_auth" && as.gha != nil:
                as.gha.DoGitHubAuth(rw, req)
```

Can you please consider supporting a configuration option of URL prefix (default '/'), so that the service safely play behind a proxy?

Docker-distribution support this as well[1]
```
http:
  addr: localhost:5000
  prefix: /my/nested/registry/
```

Thanks!

[1] https://github.com/docker/distribution/blob/master/docs/configuration.md

**Comment by rojer** [comment]
no objections. feel free to implement and send a PR, or wait until myself of someone else gets to it.

**Comment by alonbl** [comment]
Great! I will try to submit my first go patch :)

**Comment by alonbl** [comment]
Hi,
Finally I had time!
It[1] was trivial (I think), and working in our setup.
Thanks!

[1] https://github.com/cesanta/docker_auth/pull/185

**Comment by carsonoid** [comment]
I think this issue can be closed now @alonbl

**Comment by alonbl** [comment]
Hi,
Sure, it is working for me per master.
Thanks!
