### ISSUE TITLE
docker_auth behind nginx

### ISSUE THREAD

**Issue by cnluzhang** [cesanta/docker_auth#184]
I use the same domain to serve both docker_auth and registry, the nginx conf like below.

    listen 443 ssl;

    server_name docker.example.com;

    xxxx; #some certs config

    location /auth {

        proxy_pass http://docker_auth/; #run docker_auth without tls

        xxxx; #some header config

    }

    location /v2 {

        proxy_pass http://registry;

        xxxx; #some header config

    }

but when I try to login, It's return 
`Error response from daemon: Get https://docker.example.com/v2/: unable to decode token response: invalid character '<' looking for beginning of value`

So I review the nginx config, and change the location of docker_auth like below.

    listen 443 ssl;

    server_name docker.example.com;

    xxxx; #some certs config

    location / {

        proxy_pass http://docker_auth/; #run docker_auth without tls

        xxxx; #some header config

    }

    location /v2 {

        proxy_pass http://registry;

        xxxx; #some header config

    }

It works!

I'm a little confused, because I review the nginx log, I only find the request of `/auth`.
I don't want to forward all request except `/v2` to docker_auth, Is there a solution?

Thanks.

**Comment by ChipmunkV** [comment]
I'd like to do the same thing, but your solution doesn't work for me.

Could you please share all configs of the nginx, registry and the auth_server?

**Comment by eengstrom** [comment]
I just started using docker_auth today, and I have it working (sort-of) through an nginx proxy.  Technically, I have the docker registry pointing directly at the docker_auth container, rather than going through the proxy again.  

However, it could be that you are not providing the (same) SSL certs you deployed in your nginx proxy server as the certs in the docker_auth auth_config.yaml file.  If you provide that (sanitized), I might be able to help more.

**Comment by superstator** [comment]
I think your problem is the trailing slash on ` http://docker_auth/`. The absence or presence of a trailing slash tells nginx to rewrite those urls differently (I forget the exact rules). We're running successfully behind nginx with a config like so:

```
        location /v2 {
            proxy_pass              http://registry:5000/v2;
        }

        location /auth {
            proxy_pass              http://auth:5001/auth;
        }
```

and in the registry config:

```
auth:
      token:
        realm: "https://domain.io/auth"
        service: domain.io
        issuer: "Companyname"
```

**Comment by madushajg** [comment]
you may receive the same error response if your realm is incorrect.

**Comment by dyrnq** [comment]
@cnluzhang 
There are two kinds of key certificate pairs, one for docker auth server and the other for token. 
The first is necessary
The latter is must required 


I'll give you a complete configuration here. You can see the whole picture

auth.yaml
```bash
server:
  addr: ":5001"
  path_prefix: ""
  certificate: "/certs/auth-server.crt"
  key: "/certs/auth-server.key"
token:
  issuer: "docker-auth"
  expiration: 900
  certificate: "/certs/server.crt"
  key: "/certs/server.key"
```
/etc/docker/registry/config.yml
```
auth:
  token:
    issuer: "docker-auth"
    realm: "https://EXTERNAL/auth"
    service: "token-service"
    rootcertbundle: /certs/server.crt
```
nginx.conf

```bash

server {
    listen       80;
    listen       443 ssl;

    server_name  EXTERNAL;
    client_max_body_size 0;
    chunked_transfer_encoding on;
    send_timeout          600;

    ssl_certificate /path/domain.crt;
    ssl_certificate_key /path/domain.key;

    location /auth {
      proxy_pass                          https://127.0.0.1:5001/auth;
      #proxy_ssl_verify  off;
      proxy_ssl_trusted_certificate /path/certs/ca.crt;
      proxy_set_header  Host              $http_host;   # required for docker client's sake
      proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
      proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header  X-Forwarded-Proto $scheme;
      proxy_read_timeout                  900;
    }

    location /v2/ {
      if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
        return 404;
      }
      add_header 'Docker-Distribution-Api-Version' $docker_distribution_api_version always;

      proxy_pass                          http://127.0.0.1:5000;
      proxy_set_header  Host              $http_host;   # required for docker client's sake
      proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
      proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header  X-Forwarded-Proto $scheme;
      proxy_read_timeout                  900;
      proxy_connect_timeout 600;
      proxy_send_timeout    600;
      proxy_buffering off;
      proxy_request_buffering off;
    }
    
}



```
in this case , there are 3 kind key certificate pair，last for nginx。

```bash
## for docker-auth and docker-registry，you can use self signed certificates
ca.key
ca.crt
auth-server.crt
auth-server.key
server.crt
server.key
```
```bash
## for nginx , letsencrypt like that
domain.key
domain.cert
```
