### ISSUE TITLE
docker_auth/github: newly-acquired token is invalid

### ISSUE THREAD

**Issue by mgenov** [cesanta/docker_auth#189]
When I'm trying to authenticate user through Github I'm getting: "Newly-acquired token is invalid"

The logs says that app is unable to validate the organization. 
ExpiresIn:0 TokenType:bearer Error: ErrorDescription:} could not validate organization: 

Doc at:
https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-scopes-for-oauth-apps/

says that: read:org scope provides: Read-only access to organization, teams, and membership.

which is and required for the membership access. 

The scope defined in:
https://github.com/cesanta/docker_auth/blob/master/auth_server/authn/data/github_auth.tmpl#L3
is only user:email and I'm not sure that it grants organization access. 

Any thoughts about this ? 

PP: Today I'm going to build a custom image with read:org scope and will give feedback.

**Comment by mgenov** [comment]
It looks like that adding of read:org scope fixes the issue. 

Filed up PR #190 that fixes this issue.

**Comment by henti** [comment]
Good day @rojer 

Can you tag new release for this as github auth is broken otherwise and possibly update the docker image on docker hub
