### ISSUE TITLE
ACL add allow&deny keyword

### ISSUE THREAD

**Issue by summerQLin** [cesanta/docker_auth#19]
Hi Rojer,

Your current design about acl is only for allow. As long as the account is allowed by one acl entry, it will gain the access right.

Do you have ever think about deny? We could design like
* if account is denied by any acl entry, it will lose access right.
* if account isn't denied by any acl entry, and allowed by one acl entry, it'll gain access right.

Is this design reasonable to you?

Thanks

**Comment by summerQLin** [comment]
Another question is, should acl entries be configured as mutually exclusive?

**Comment by rojer** [comment]
re: allow/deny - what is possible today is to deny everything to account by creating an ACL with actions: [] (i.e. empty set). you can match on any name, so "actions: []" is more or less the equivalent of "deny".

i think your proposal as i understand it is already implemented. just use an entry with "actions: []" whenever you want to deny something and it'll work.

**Comment by summerQLin** [comment]
Hi rojer,
Thanks for your reply.

I should have an example to explain my requirement here. If you could advise me how to achieve it by means of current design, that will be very nice. Otherwise I propose my solution for you to review.

Requirement:
One account e.g. "rojer" should be bound to path "cesanta/", so that others can't push to repository cesanta/.  I figured out the way to write auth_config.yml
```
- match: {account: "/.+/", name: "/^(?!cesanta/).+/"}
  actions: ["*"]
- match: {account: "rojer", name: "/^cesanta/.+/"}
  actions: ["*"]
```
meaning any user will pull/push images not start with "cesanta/", user rojer will pull/push any images.
Unfortunately, Go regexp doesn't support negative lookahead. So expression ^(?!cesanta/).+/ must encounter error.

I propose a way to deny user from accessing images start with cesanta/, for example
```
- match: {account: "/.+/", name: "/^cesanta/.+/", name-reverse: true}
```
Thus func matchString("someone", "/^cesanta/.+/") will be false because it actually returns !matched since name-reverse is true.

**Comment by rojer** [comment]
acls are evaluated in order and the serahc terminates on first match.
this, you can achieve your goal by the following sequence of acls:
1) give the special user full access to cesanta/.+:
  match: {account: "rojer", name: "/^cesanta/.+/"}
  actions: ["*"]
2) deny access to cesanta/.* to everyone, which will effectively everyone _else_, because rojer will match in the previous ACL
  match: {name: "/^cesanta/.+/"}
  actions: []

thus, rojer will have full access, but everyone else will be denied.
does this solve your problem? if yes, then i think a clarification in the doc and perhaps an example like the one above will be sufficient.

**Comment by summerQLin** [comment]
For step 2), to deny access to cesanta/.*, that's why I proposed the way to deny some paths' accessibility for some user.
  `match: {name: "/^cesanta/.+/"}` means anonymous user will be allowed if matching /^cesanta/.+/
And `match: {name: "/^cesanta/.+/", name-reverse:true}` means anonymous user will be denied if matching /^cesanta/.+/

**Comment by summerQLin** [comment]
Or probably you'd better to choose a better key word for the purpose.

**Comment by rojer** [comment]
anonymous user will indeed match the `{name: "/^cesanta/.+/"}` rule but it will be denied, like everyone else, because the set o allowed actions is empty.

**Comment by summerQLin** [comment]
Ok, that's really great idea. It's very helpful. 
Thanks.

**Comment by rojer** [comment]
cool. i made it more explicit in the doc.

**Comment by summerQLin** [comment]
Hi Rojer,
Your deny method is really great for simple scenario. But mine seems more complex...
I found an issue here. If I do it like what you suggest, probably I'll get config like
```
- match: {name: "/^cesanta/.+/", account: "rojer"}
  actions: ["*"]
- match: {name: "/^cesanta/.+/", account: "/.+/"}
  actions: [ ]
```
This is helpful to protect cesanta/ repo from being pushed by user other than rojer.

However, if there comes another user called 'userA' should have pull/push right to pathA, pathB, pathC...(countless paths) except cesanta/. Obviously from this configuration, userA doesn't match entry[0] or entry[1], so userA's pushing to pathA will be rejected. That's not right.

I don't know if this requirement is strange to you or not. I really hope to hear your opinion about this.
