### ISSUE TITLE
docker_auth/github/proposal: per team authorization

### ISSUE THREAD

**Issue by mgenov** [cesanta/docker_auth#191]
## Problem
ACL matching of Github authorization requires per user restriction which requires acl's accounts to be hardcoded in the configuration. The acl configuration need to be added or removed regarding change of the user. 

## Proposal
As labels are used by the ACL for matching it would allow Github authorization to provide teams to which user is assigned in that organization. As teams are much rarely changed then users it would be easier for applying ACL users for them 

Github has an API for listing of user-teams:
https://developer.github.com/v3/orgs/teams/#list-user-teams

which will provide a list of all teams for a given users in all organizations. The filter for the selected organization could be made inline in code so only teams of the selected organization to be added as labels. 

Currenly the Authenticate function of Github is defined as: 
```golang
func (gha *GitHubAuth) Authenticate(user string, password PasswordString) (bool, Labels, error) {
	err := gha.db.ValidateToken(user, password)
	if err == ExpiredToken {
		_, err = gha.validateServerToken(user)
		if err != nil {
			return false, nil, err
		}
	} else if err != nil {
		return false, nil, err
	}
	return true, nil, nil
}
```
e.g the Authenticate calls returns and labels.  

My proposal is this call to return and label Teams which to contain a list of teams to which user is assigned to. 

"Teams" => ["Team1", "Team2"]

By doing this the ACL will be able to match per Team credentials instead of per User.

**Comment by mgenov** [comment]
I'm open to contribute this change if team accepts the proposed solution.

**Comment by karmi** [comment]
Update from this week:

* We have improved the `Makefile`, cutting the time to build the project by more than half
* We have hit an issue where a [popular Go library](https://github.com/jteeuwen/go-bindata)
  dissapeared from Github (sic!), working around it
* We have solved the issues with dependencies by using ``govendor sync -v`
* We have extracted every separate functionality into a special branch, prefixed with `pr/`,
  to prepare a clean code suitable for contributing to upstream.
* We have cleaned up _all the commits_, squashing them into logical chunks, rewriting all
  commit messages, running `go fmt` on the source, and verifying our changes build sucessfully

Right now, we have [4 separate branches](https://github.com/dliappis/docker_auth/branches/all?query=pr)
corresponding to the four major features we have added to the project:

1. [**Build improvements**](https://github.com/dliappis/docker_auth/compare/master...pr/build-improvements)
2. [**Adding labels into user tokens**](https://github.com/dliappis/docker_auth/compare/master...pr/store-labels-in-token)
3. [**Fetching user's Github teams into labels**](https://github.com/dliappis/docker_auth/compare/master...pr/github-teams)
4. [**Storing tokens in Redis**](https://github.com/dliappis/docker_auth/compare/master...pr/tokendb-redis)

We have created a [script](https://github.com/cesanta/docker_auth/files/1704181/branch_mashup.sh.txt) to combine the branches into a single one, which is used for building the binary with all the features.

We have verified locally that the Github authentication works, that the user's teams are correctly stored in the token, that the information is encrypted, and most importantly, that the configured permissions conform to expectations.

Next week, we want to:

* Submit pull requests to the upstream project at <https://github.com/cesanta/docker_auth>
* Deploy a version of the project with all features to the test Docker registry, and verify the functionality in a more realistic environment.

**Comment by rojer** [comment]
i believe @karmi nailed this one
