### ISSUE TITLE
are labels in YAML config file ACL specifications in the latest docker image

### ISSUE THREAD

**Issue by eengstrom** [cesanta/docker_auth#202]
I just started using docker_auth today - worked quickly out of the box, that is until I tried to use the labels as exampled in https://github.com/cesanta/docker_auth/blob/master/docs/Labels.md, but I could not get them to work.  I tried both the stable (:1) and :1.3 tags of the docker image, but neither seemed to work.  I didn't dig any further, such as trying a source build, but will if someone can tell me that it should be working.  I can of course provide more details if needed as well.

**Comment by carsonoid** [comment]
Can you post your config?

**Comment by eengstrom** [comment]
Config:
    
    server:
      addr: ":5001"
      certificate: "/certs/cert-bundle.pem"
      key: "/certs/cert.key"
    
    token:
      # Issuer *MUST* match issuer in the Registry config.
      issuer: "Docker Auth Server"
      expiration: 900
    
    users:
      # Password is specified as a BCrypt hash.
      # Use `htpasswd -B` to generate.
      # For 'labels' (e.g. groups/projects) see also
      # -- https://github.com/cesanta/docker_auth/blob/master/docs/Labels.md
    
      "test":
         password: "$2y$05$WuwBasGDAgr.QCbGIjKJaep4dhxeai9gNZdmBnQXqpKly57oNutya"  # 123
         labels: {
            group: [ "group1" ],
            project: [ "proj1", "proj2" ],
            tier: [ "foo", "bar" ]
         }
         # Also tried this:
         #labels: 
         #  group:
         #   - "group1"
         #  project:
         #    - "proj1"
         #    - "proj2"
    
      # Allow anonymous (no "docker login") access
      #"": {} 
    
    acl:
      # First match counts, so put most specific first
      
      # --- CATALOG - Allow catalog access (for docker-ls, e.g.)
      - match: {account: "/.+/", type: "registry", name: "catalog"}
        actions: ["*"]
        comment: "Logged in users can query the catalog."
    
      # --- hello-world (testing)
      # ANY (incl. anonymous) pull of hello-world (only if anon access allowed).
      - match: {name: "hello-world", account: ""}
        actions: ["pull"]
        comment: "Anonymous in users can pull \"hello-world\"."
      
      # --- Project access, by project, and account (regexp)
      # Want to be able to use labels like this:
      # 
      # Allow project access for ALL users
      - match: {name: "${labels:project}/*"}
        actions: ["push", "pull"]
        comment: "Users can push/pull to any project to which they are assigned."
    
      ## Allow user/account access in a group access to user-specific images:
      - match: {account: "/.+/", name: "${labels:group}/${account}/*"}
        actions: ["*"]
        comment: "Logged in users have full access to images that are in their personal 'group/namespace'"
    
      #ADMIN
      - match: {account: "admin"}
        actions: ["*"]
        comment: "Admin has full access to everything."
    
      # DEFAULT: Access is denied by default.

**Comment by rojer** [comment]
@carsonoid go ahead with the PR, i can make a point release with the fix

**Comment by carsonoid** [comment]
Sounds good. I'll work on that feature add.

**Comment by carsonoid** [comment]
@rojer PR #206 fixes this. and PR #199 fixes another small bug when using labels in regex

**Comment by rojer** [comment]
i pushed `-latest`, will let it brew there for a while before cutting `1.3`
