### ISSUE TITLE
LetsEncrypt cache_dir not used?

### ISSUE THREAD

**Issue by Phlamethrower** [cesanta/docker_auth#204]
If you're using LetsEncrypt, you're required to specify a cache_dir value in the config file, but when LetsEncrypt is being initialised it doesn't look like the value is actually used.

https://github.com/cesanta/docker_auth/blob/master/auth_server/server/config.go#L228
https://github.com/cesanta/docker_auth/blob/master/auth_server/main.go#L79

**Comment by rojer** [comment]
oops, true. fixing now!
