### ISSUE TITLE
get curl inside docker_auth container

### ISSUE THREAD

**Issue by tabka** [cesanta/docker_auth#215]
I want to allow users to access the registry from an external api so I would like to use curl inside ext_auth.sh 
example:
```
#!/bin/sh
#
# Example external authenticator program for use with `ext_auth`.
#

read u p

curl 'http://api:8888/check_cloud?docker_username=$u&docker_password=$p'|grep allow
result=$?

if [ $result -eq 0 ]; then
  echo '{"labels": {"pull-only-access" : ["*"]}}'
  exit 0
fi

exit 1
```

But inside the container there's no way to get curl.
So is there a way to use the docker_auth server and make it contact an external api.

Thank you for your help

**Comment by carsonoid** [comment]
You would need to build your own version of the image based on a larger distro with a package manager.

I would suggest that you pull down the repo, edit the [dockerfile](https://github.com/cesanta/docker_auth/blob/master/auth_server/Dockerfile) to be based on something like alpine so that you have a proper package manager. Then you can add a line to install curl.

It would be something like this:

```
FROM alpine
RUN apk update && apk add curl
ADD auth_server /docker_auth/
COPY ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
ENTRYPOINT ["/docker_auth/auth_server"]
CMD ["/config/auth_config.yml"]
EXPOSE 5001
```

**Comment by tabka** [comment]
Thank you very much , it works perfectly.
I thought about it in the beginning but I missed the fact that I can build the auth_server binary by my self with the Makefile. And now everything is working as required.

**Comment by JacobTheEvans** [comment]
Hey guys,
Just came across this thread and took the advice from @carsonoid to download the library and mount it in alpine so I could also use curl. I wanted to share my specific docker file implementation in case anyone else comes across this thread.
```
FROM golang@sha256:cf0b9f69ad1edd652a7f74a1586080b15bf6f688c545044407e28805066ef2cb AS builder
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install python-pip git -y && \
    pip install gitpython && \
    mkdir -p /var/tmp/go/src/github.com/cesanta

WORKDIR /var/tmp/go/src/github.com/cesanta
RUN git clone https://github.com/cesanta/docker_auth.git

ENV GOPATH=/var/tmp/go
ENV PATH=$PATH:$GOPATH/bin

WORKDIR /var/tmp/go/src/github.com/cesanta/docker_auth/auth_server
RUN make deps && make generate && make

FROM alpine@sha256:02c076fdbe7d116860d9fb10f856ed6753a50deecb04c65443e2c6388d97ee35
RUN apk --no-cache add curl
RUN mkdir /docker_auth
COPY --from=builder /var/tmp/go/src/github.com/cesanta/docker_auth/auth_server/auth_server /docker_auth/auth_server
RUN chmod +x /docker_auth/auth_server
ENTRYPOINT ["/docker_auth/auth_server"]
CMD ["/config/auth_config.yml"]
EXPOSE 5001
```
