### ISSUE TITLE
What is the time unit of  this tag ?. Is it for Access token or Refresh token ? 

### ISSUE THREAD

**Issue by ThilinaManamgoda** [cesanta/docker_auth#216]
https://github.com/cesanta/docker_auth/blob/509a03a9622f460ded806a2c7b7b27717b3cb1f5/examples/reference.yml#L47

**Comment by carsonoid** [comment]
Seconds.

It's just an integer that get's added to the unix epoch at the time of token creation: https://github.com/cesanta/docker_auth/blob/dd8ea4b8429b5e31bf102f77fdda866186e2cb6f/auth_server/server/server.go#L302
