### ISSUE TITLE
Webhook by acl

### ISSUE THREAD

**Issue by scampion** [cesanta/docker_auth#226]
Idea:  For each acl, you can configure a webhook

Each time, this acl is requested a JSON payload is sended to the webhook endpoint (status : success, user: john ...etc) 

This feature is really useful if you want to integrate docker_auth in an complex process pipeline. 

For my usage, we need to update our data when a push is done. 

I'm not a go developer but i will try to hack, if you have any suggestion, please dont hesitate

**Comment by techknowlogick** [comment]
@scampion Docker Registry has many different types of notifications already available, perhaps you it would be better if you looked at those first. See: https://docs.docker.com/registry/notifications/

**Comment by techknowlogick** [comment]
Closing, please feel free to re-open as needed.
