### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by mrueg** [cesanta/docker_auth#227]
Can you tag a new release? @rojer 

Thanks!

**Comment by rojer** [comment]
done: https://github.com/cesanta/docker_auth/releases/tag/1.3.1

**Comment by mrueg** [comment]
Thanks a bunch!

**Comment by fxdgear** [comment]
@rojer can you tag a new release again? There's been 2 new patches merged that I'd like to start testing with. Thanks
