### ISSUE TITLE
Can docker_auth work with docker login?

### ISSUE THREAD

**Issue by gabrieloshiro** [cesanta/docker_auth#230]
Hi,

I would like to allow users to log in my private registry using their google accounts. I've set up `docker_auth` up to the point where I can navigate to `https://<MY_DOMAIN>:5001/` then there will be a link to login with google account. After logging in I get the following message "Server logged in; now run "docker login YOUR_REGISTRY_FQDN", use <EMAIL_ACCOUNT> as login and <PASSWORD> as password."

When I run `docker login https://<MY_DOMAIN>:5000/` on the command line and I input the login and password proposed, I get the following message:

> Error response from daemon: Get http://<MY_DOMAIN>:5000/v2/: unable to decode token response: invalid character '<' looking for beginning of value

How can we make this work? Can we completely by-pass the browser and just do everything on the command line? If so, why do I get redirected to HTTP instead of HTTPS when I log in? And why do I get redirected to `/v2/`?

Thank you in advance

**Comment by techknowlogick** [comment]
It is possible to login with Google accounts currently. Could you provide a sanitized version of your auth_server config, and docker-registry config?

**Comment by techknowlogick** [comment]
Closing, but please feel free to re-open if you are still facing this issue.
