### ISSUE TITLE
token auth requires now a new option bool: autoredirect

### ISSUE THREAD

**Issue by mb3dot** [cesanta/docker_auth#245]
Hi,

the new Docker Registry 2.7 *needs* now the new option bool: autoredirect

for example: 
------ registry config.yml ----------------------------
auth:
   token:
      realm: https://registry.example.com:5001/auth
      autoredirect: false
      service: docker registry
      issuer: acme auth server
      rootcertbundle: /path/to/server.pem
------ registry config.yml ----------------------------

without comes the following error message:
panic: unable to configure authorization (token): token auth requires a valid option bool: autoredirect

and here is the commit on github from docker..
https://github.com/docker/distribution/commit/f730f3ab77d0098f5172a825d9feecc6265f3c48

**Comment by rojer** [comment]
so this is about registry config, not auth server, right?

**Comment by mb3dot** [comment]
yes, but `docker_auth/examples/reference.yml` needs an update..

and the new autoredirect generate url's like `realm = fmt.Sprintf("https://%s/auth/token", r.Host)` and would be a nice feature when the registry and docker_auth are behind a reverse proxy..

**Comment by rojer** [comment]
fair enough, example updated.

so what would supporting the redirect entail? sorry, it's been a while since i've looked into this, need a bit of paging in of context. do we need to implement `/auth/token` endpoint in docker auth?

**Comment by mb3dot** [comment]
yes!.. : ) that would be very useful..  otherwise, this cool new function would be useless.. and that would be a pity..

**Comment by alexivkin** [comment]
An easy workaround is to set REGISTRY_AUTH_TOKEN_AUTOREDIRECT=false for your registry:2.7+
