### ISSUE TITLE
LDAP: option to initially bind with user credentials

### ISSUE THREAD

**Issue by aparamon** [cesanta/docker_auth#246]
Currently, LDAP auth works like this:
1. Bind without credentials or using service credentials:
https://github.com/cesanta/docker_auth/blob/1e138837a652d45b2278a457ec0698985e0190e3/examples/reference.yml#L139-L142
2. Search using specified filter,
3. Bind with user credentials.

It is proposed to introduce additional option to bind with user credentials initially (assuming users can search filter). The flow would be:
1. Bind with user credentials,
2. Search using specified filter.

**Comment by rojer** [comment]
sounds reasonable. a PR that does this in a backward-compatible manner will be accepted.
so, perhaps a boolean option `bind_with_user_creds` or some such.
i have no time to devote to this though, so unless there's a PR this is not happening any time soon.

**Comment by aparamon** [comment]
A bit lower-hanging fruit (and somewhat orthogonal but related feature) is to allow `${account}` expansion in `bind_dn`, plus option to use account password for initial bind.

**Comment by techknowlogick** [comment]
Closed per #309 being merged :)
