### ISSUE TITLE
Error authorizing context: invalid token

### ISSUE THREAD

**Issue by makbn** [cesanta/docker_auth#249]
Hi, I tried to login with reg.mydomain.com:5000/auth and got this token:

```json
{
    "token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6I...."
}
```

and after that I tried to call `/v2/` endpoint on my reg domain with `Authorization : Bearer eyJ0eXAiOiJKV1...` i still get `401 Unauthorized` exception and container logs are shows **authorizing context: invalid token**:

```bash
ime="2019-03-09T13:02:30.057563083Z" level=info msg="token from untrusted issuer: "Acme auth server"" 
time="2019-03-09T13:02:30.057734804Z" level=warning msg="error authorizing context: invalid token"
go.version=go1.11.2 http.request.host=reg.mydomain.com http.request.id=591459f9-990b-4263-843b-7017af3ffa08 http.request.method=GET 
http.request.referer="https://reg.mydomain.com/v2"
http.request.remoteaddr="1**.1*.*1.182:52760" http.request.uri="/v2/" http.request.useragent="PostmanRuntime/7.3.0" 

1**.1*.*1.182 - - [09/Mar/2019:13:02:30 +0000] "GET /v2/ HTTP/1.1" 401 87 "https://reg.mydomain.com/v2" "PostmanRuntime/7.3.0"

```

and my response header:

`Www-Authenticate →Bearer realm="https://reg.mydomain:5000/auth",service="my docker reg",error="invalid_token"`

i tried `token:eyJ0eXAiOiJKV1...` too but I faced to same problem!

**Comment by dennismeissel** [comment]
I'm facing the same problem, if I'm trying to send requests manually.
Although, "docker login" command in CLI works properly.

@makbn, did you find a solution?

**Comment by dennismeissel** [comment]
I solved it by me. I've forgot to add "service" and "scope" to request parameters.

A hint:
The reason, why the request was unsuccessful, you can find by the end of the "Www-Authenticate" header in respone (there is a field "error").
