### ISSUE TITLE
Reason for spawning a new process in authentication and authorization extensions ?

### ISSUE THREAD

**Issue by tharindulak** [cesanta/docker_auth#253]
I have been using docker auth authorization and authentication extension for a project. I have observed that for each and every authentication request, a **new process is spawned**. This result  in higher resource consumption. Is there a particular reason for implementing like this, without giving the developer to add a plugin (Or at least communicate through UNIX socket) ? Introducing a plugin may avoid spawning a new process. 
Thank you ..!

**Comment by rojer** [comment]
ext_authn/autz is meant for quick hacks / low volume usage cases.
next step currently is implementing the [Authenticator](https://github.com/cesanta/docker_auth/blob/master/auth_server/authn/authn.go) or [Authorizer](https://github.com/cesanta/docker_auth/blob/master/auth_server/authz/authz.go) interface in the source.
i agree that there is a place for an intermediate option for a shared library or socket interface. the reason it doesn't exist is that no one had the need or time to implement it yet. you are welcome to do so.

**Comment by tharindulak** [comment]
I have implemented a new custom authentication and authorization mechanism where the developers can add their own plugins to existing docker auth implementation. As you mentioned in the comment, I implemented the authenticator and authorizer interfaces in doing so. I did it like that to make this backward compatible with the existing users. I have tested this new authentication and authorization implementations with my [authentication](https://github.com/tharindulak/docker-auth-custom/blob/master/authn_plugin.go) and [authorization](https://github.com/tharindulak/docker-auth-custom/blob/master/authz_plugin.go) [plugins](https://github.com/cesanta/docker_auth). 
Please review this **[PR](https://github.com/cesanta/docker_auth/pull/254)** and merge
Highly appreciated if you can review this quickly and merge since I am going to use docker auth implementation for a production project at [WSO2](https://wso2.com/). 
If we can get this merge I will write the necessary documentation and examples to use the new implementation as the already existing docs in your repo.   
Thank you ..!

**Comment by tharindulak** [comment]
I have fixed the comments for the [PR](https://github.com/cesanta/docker_auth/pull/254). I had a question there. Please review those changes and let me know further changes.
Thank you ..!

**Comment by hasinthaindrajee** [comment]
Hi @rojer 

It would be great if you can help us to get this merged and released since one of our solutions needs this improvement.

**Comment by rojer** [comment]
@hasinthaindrajee i assume you were talking about https://github.com/cesanta/docker_auth/pull/254
reviewed, still some work necessary to get it in.

**Comment by tharindulak** [comment]
Hi @rojer 
I have done the remaining necessary fixes. Can you please review it and merge?

**Comment by hasinthaindrajee** [comment]
Hi @rojer , Thanks for helping out to get the PR merged. Any idea when we can get the repo released with this change ?

**Comment by rojer** [comment]
let me take a look at some other PRs and i'll push latest

**Comment by rojer** [comment]
built and pushed `cesanta/docker_auth:latest`
