### ISSUE TITLE
Logging from go lang authn ext

### ISSUE THREAD

**Issue by belsakn** [cesanta/docker_auth#255]
Hello, 

I'm trying to implement custom authentication extention with go lang.
When i try to log something with `fmt.Println("some test")` i'm getting this error: `authn #1 returned error: invalid character 's' looking for beginning of value` 

Any suggestions?

**Comment by techknowlogick** [comment]
Hi @belsakn Are you using `ext_auth` or `plugin_authn`?

**Comment by belsakn** [comment]
Hey, I solved this but can't remember how, since this was a long time ago, I will just close this issue
