### ISSUE TITLE
Glog reinitializes and fails in custom auth plugins

### ISSUE THREAD

**Issue by tharindulak** [cesanta/docker_auth#257]
Hi,

I am facing an issue in using authn and authz plugins due to glog reinitialization. In this docker_auth implementation in the main function, it parses a [flag](https://github.com/cesanta/docker_auth/blob/f1a115f5e2a7f6ce2d4fc07b833bf2c704fdf3e8/auth_server/main.go#L159). Then when using the plugin, since we had to use authn and authz packages (to implement the interfaces) glog tries to initialize again. I am appending my error at the end. 
So I had two solutions, one is to remove glog and use another logger. Another solution was to separate the two interfaces from auth and authz plugins. So I think the best approach is to separate two interfaces for more clarity.

Log when trying to run the main function. 

./main flag redefined: log_dir
panic: ./main flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000030180, 0x494d4c0, 0xc000142d80, 0x958bc1f, 0x7, 0x95a12fd, 0x2f)
        /usr/local/Cellar/go/1.12.5/libexec/src/flag/flag.go:850 +0x4ca
flag.(*FlagSet).StringVar(...)
        /usr/local/Cellar/go/1.12.5/libexec/src/flag/flag.go:753
flag.(*FlagSet).String(0xc000030180, 0x958bc1f, 0x7, 0x0, 0x0, 0x95a12fd, 0x2f, 0xc000142d70)
        /usr/local/Cellar/go/1.12.5/libexec/src/flag/flag.go:766 +0xa5
flag.String(0x958bc1f, 0x7, 0x0, 0x0, 0x95a12fd, 0x2f, 0xc00029b858)
        /usr/local/Cellar/go/1.12.5/libexec/src/flag/flag.go:773 +0x6c
github.com/cellery-io/docker-auth-custom/vendor/github.com/cesanta/glog.init.ializers()
        /Users/tharindu/go/src/github.com/cellery-io/docker-auth-custom/vendor/github.com/cesanta/glog/glog_file.go:41 +0xe9
plugin.open(0xc000370000, 0x45, 0x46eeca0, 0xc00007e600, 0xc00029bb58)
        /usr/local/Cellar/go/1.12.5/libexec/src/plugin/plugin_dlopen.go:103 +0xad6
plugin.Open(...)
        /usr/local/Cellar/go/1.12.5/libexec/src/plugin/plugin.go:32
github.com/cesanta/docker_auth/auth_server/authn.lookupSymbol(0xc000142260, 0xc000132100, 0xc00036c070, 0x481d960, 0xc00007e600)
        /Users/tharindu/go/src/github.com/cesanta/docker_auth/auth_server/authn/plugin_authn.go:32 +0x4d
github.com/cesanta/docker_auth/auth_server/authn.(*PluginAuthnConfig).Validate(...)
        /Users/tharindu/go/src/github.com/cesanta/docker_auth/auth_server/authn/plugin_authn.go:53
github.com/cesanta/docker_auth/auth_server/server.validate(0xc00007e600, 0x1ee, 0x3ee)
        /Users/tharindu/go/src/github.com/cesanta/docker_auth/auth_server/server/config.go:165 +0x3cc
github.com/cesanta/docker_auth/auth_server/server.LoadConfig(0x7ffeefbff39f, 0x15, 0x4e97e20, 0x1, 0x0)
        /Users/tharindu/go/src/github.com/cesanta/docker_auth/auth_server/server/config.go:203 +0x344
main.main()
        /Users/tharindu/go/src/github.com/cesanta/docker_auth/auth_server/main.go:169 +0x14 

Thank you

**Comment by tharindulak** [comment]
This [PR](https://github.com/cesanta/docker_auth/pull/258) will fix the issue. Please review this and merge.

**Comment by tharindulak** [comment]
Hi @rojer ,

I have fixed the comments, please review and merge. 
Can we get a release with a specific **tag** for this plugin implementation?

**Comment by rojer** [comment]
thanks for doing this.
https://github.com/cesanta/docker_auth/pull/258 has been merged.
cesanta/docker_auth:latest has been pushed that contains this change.
