### ISSUE TITLE
Error invalid scope

### ISSUE THREAD

**Issue by jamct** [cesanta/docker_auth#268]
I am working on an issue with helm v3, trying to push a chart to my docker v2 registry (with this auth server).
Helm is using deislabs/oras for connecting with the registry. This library combines multiple scopes with a space char (it is always the same repo with different actions).
 This is correct and described here:
[Distribution spec](https://github.com/docker/distribution/blob/1b9ab303a477ded9bdd3fc97e9119fa8f9e58fca/docs/spec/auth/scope.md#authorization-server-use)

> The POST request only takes in a single scope field but may use a space to separate a list of multiple resource scopes.

Cesanta/docker_auth is not ready for this kind of scope and returns "invalid scope" in "/docker_auth/server.go" (line 229).

I would like to prepare a patch and need some input: I would split by spaces and check if it's always the same repository. Afterwards I would combine all actions (like push and pull). I can't imagine a scenario
where a client needs access to multiple repos in one request.

**Comment by Ka0o0** [comment]
I think this has already been address in #274 .
