### ISSUE TITLE
docker plugin push fails with insufficent scope

### ISSUE THREAD

**Issue by fxdgear** [cesanta/docker_auth#269]
I'm trying to figure out why I can't push a plugin to my registry with auth provided by this project.

when I push an image everything works fine. When I push a plugin I get an error insufficient scope. 

I tried reading through the auth section of this project but it doesn't seem to really call out any particular scope types inparticular so I figure it should be pretty generic, as long as you're properly conforming to the grammar. (which you reference that you are). 

So, I was wondering if there's any flags I need to change or anything in particular I should be made aware of when using docker_auth for pushing plugins into my repository. 

Thanks

**Comment by rojer** [comment]
i'm not familiar with plugins, maybe they require additional auth scopes.
[this documents](https://docs.docker.com/registry/spec/auth/scope/) describes a `repository(plugin)` resource type. maybe we need a token for that resource.
i don't have time to investigate though, so if someone figures this out and sends a PR - great.
