### ISSUE TITLE
New Release Please

### ISSUE THREAD

**Issue by fxdgear** [cesanta/docker_auth#271]
@rojer 

Would you be willing to cut a new release/docker image for this project? 

Thanks

**Comment by rojer** [comment]
well, i wish i could but it seems i no longer have credentials for cesanta docker hub - i no longer work there, after all.
i'll reach out to them to figure out what to do, but for now i just can't.

**Comment by fxdgear** [comment]
ahh ok.  :( Let me or @flaper87 know if there's anything we can help to either keep the project moving forward/maintaining and releasing :)

**Comment by rojer** [comment]
actually, i figured it out - this was problem with my docker installation, it wasn't properly authenticating to docker hub, even though docker login was succeeding.
i have now pushed `:latest` with the change.

**Comment by halkeye** [comment]
Is latest the same as 1.6.0?
