### ISSUE TITLE
Error on non JSON output from External Authentication program.

### ISSUE THREAD

**Issue by ankushChatterjee** [cesanta/docker_auth#279]
Error is thrown if the console output of the external authentication program is not in JSON format of `ExtAuthResponse`. The code is :-

https://github.com/cesanta/docker_auth/blob/99bfe0217f59ee1fa43596f5be4af14a521f1f17/auth_server/authn/ext_auth.go#L87

External authorization console output does not have these requirements.
This is a bit problematic when the program does some custom logging on the console, especially during development. 

_A small proposal_ from my side is taking perhaps the last line (output split by \n) for the JSON representation, I understand this may break some existing applications where the JSON is given as a multiline output.

_Another solution might be_, that the custom logging lines must carry a predefined tag which has to be prepended to the logging line. Eg:-

`[EXT_AUTH_LOG] Credentials loaded from the database. `

These lines can be exempted when considering the JSON representation. 
Apologies if I am not making sense in the context of specific to the design goals / specific use cases of the project. Would love to learn more about this.

**Comment by rojer** [comment]
docker_auth only uses stdout for json.
as long as your script emits diagnostic output to stderr, as a well-behaved program should, it'll be fine. i am not inclined to change our external program protocol to accommodate misbehaving programs.
multi-line JSON output is perfectly valid and should be supported.
introducing an "ignore prefix" seems hacky too.

**Comment by ankushChatterjee** [comment]
Thanks for pointing me to the right direction. Much appreciated.
