### ISSUE TITLE
Unable to configure letsencrypt

### ISSUE THREAD

**Issue by sivaramsk** [cesanta/docker_auth#286]
Below is the auth_config.yaml I am using 

`server:
  addr: ":5001"
  certificate: "/registryconfig/tls.crt"
  key: "/registryconfig/tls.key"

token:
  issuer: "Acme auth server"  # Must match issuer in the Registry config.
  expiration: 900

letsencrypt:
    # Email is required. It will be used to register with LetsEncrypt.
    email: sivaramsk@gmail.com
    # Cache directory, where certificates issued by LE will be stored. Must exist.
    # It is recommended to make it a volume mount so it persists across restarts.
    cache_dir: /data/sslcache
    # Normally LetsEncrypt will obtain a certificate for whichever host the client is connecting to.
    # With this option, you can limit it to a specific host name.
    host: "blueforge.eastus.azurecontainer.io" 
`
I assume that I do not need certification and key to be configured when I use letsencrypt, but if I remove the certificate and key from the configuration the container does not come up. But if I configure the certificate and key with selfsigned certificate, the registry is still insecure and I get the error "x509: certificate signed by unknown authority".

If letsencrypt is configure correctly, I should not see the error and I need not add the registry as insecure to docker config right? How do I correctly configure letsencrypt?

**Comment by techknowlogick** [comment]
I don't think LE is working if you have certfile and keyfile set, per this conditional https://github.com/cesanta/docker_auth/blob/3fb13f1d7eb9bbe0285c3877ed1938e39609e1af/auth_server/main.go#L100 

It could be that LE when you have the correct config for LE to activate it won't as you aren't listening on port 443 per the tls-alpn-01 challenge type requirement https://letsencrypt.org/docs/challenge-types/#tls-alpn-01

Could you try having auth_server listen on port 443 to see if LE is able to provision a certificate for you?

**Comment by techknowlogick** [comment]
Closing, but if the above doesn't work please re-open :)
