### ISSUE TITLE
Any plans for new Docker Image Release?

### ISSUE THREAD

**Issue by gabrielcalderon** [cesanta/docker_auth#288]
Any plans for a new release in Docker Hub? Last image was pushed over 7 months ago.

**Comment by rojer** [comment]
sorry, i'm totally, completely out of time to devote to this project... in fact, i'm not even using it myself anymore.

**Comment by techknowlogick** [comment]
@rojer need some help? I use it daily and have contributed to this project before.

**Comment by rojer** [comment]
i do, yeah. i'd like someone to become primary maintainer for this project.

**Comment by techknowlogick** [comment]
Happy to be that person. My OSS experience includes: one of the project leads for Gitea (21K+ stars), maintain several other projects, plus contribute to even more.

**Comment by rojer** [comment]
thanks! i invited to the project. please attend to issues and pull request. if that goes well, i'll give you push access.

**Comment by gabrielcalderon** [comment]
Looking forward to all new fixes/updates!

**Comment by techknowlogick** [comment]
Thanks @rojer :)

**Comment by gabrielcalderon** [comment]
@rojer What would be required to push a new image to Docker Hub? Do you still have the creds to that account?

**Comment by techknowlogick** [comment]
In addition to the github action I wrote for testing GO, I could also write one that automates the publishing of the image on merge to master (where it will use the "lastest" label) and on tag (where the image will be named the same as the git tag.

The credentials could be managed in GH settings so I wouldn't need access to them.

**Comment by gabrielcalderon** [comment]
@techknowlogick That would be an ideal solution!

**Comment by rojer** [comment]
sounds good, go ahead

**Comment by techknowlogick** [comment]
@gabrielcalderon A new image has now been pushed.

**Comment by gabrielcalderon** [comment]
@techknowlogick Thanks you! 👍🏻
