### ISSUE TITLE
Authentication fail

### ISSUE THREAD

**Issue by summerQLin** [cesanta/docker_auth#3]
I am so excited to see registry v2's authentication server's built up! But I couldn't pass authentication. 

When I run: docker push localhost:5000/test-busybox   
<code>FATA[0003] Error response from daemon: no successful auth challenge for http://localhost:5000/v2/ - errors: [token auth attempt to http://localhost:5000/v2/ realm "https://127.0.0.1:5001/auth" failed with status: 401 Unauthorized]</code>

When I run: docker push localhost:5000/test/test-busybox
<code>FATA[0000] Error pushing to registry: token auth attempt for registry http://localhost:5000/v2/: https://127.0.0.1:5001/auth?account=test&scope=repository%3Atest%2Ftest-busybox%3Apull%2Cpush&service=Docker+registry request failed with status: 403 Forbidden</code>

My auth_config.yml setting for account 'test'
<pre><code> "test":
    password: "$2a$05$oU4jdJOakJaUYKkfXY06jul6EneXPXtCeyZf2davojiNaocyFxCKW" 
  ...
   - match: {account: "test", name: "test-*"}
    actions: ["*"]
   - match: {account: "test"}
    actions: []</code></pre>
I don't know whether it's code issue or my config's wrong.

**Comment by rojer** [comment]
can you increase verbosity? pass --v=2 (before the config name) to the
server and it should print more diagnostic information (why request was
declined).

**Comment by rojer** [comment]
did it work for you in the end?

**Comment by summerQLin** [comment]
Not sure about verbosity mode. But registry container's log says:
<pre><code>
172.*.*.* - - [03/Jun/2015:05:27:41 +0000] "GET /v2/ HTTP/1.1" 401 114 "" "docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-48-generic os/linux arch/amd64"
DEBU[9845] authorizing request                           environment=development http.request.host=localhost:5000 http.request.id=9abaf613-1276-4338-b1b7-ea531dd668d9 http.request.method=GET http.request.remoteaddr=172.*.*.*:50655 http.request.uri=/v2/ http.request.useragent=docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-48-generic os/linux arch/amd64 instance.id=f785d636-e7bf-492b-9e62-8a6c329c4e73 service=registry version=v2.0.0-179-g3073b1d.m
ERRO[9845] token signed by untrusted key with ID: "3N4K:I5AH:Y73O:42OE:GTGV:H5HZ:PUXH:QF3Z:BIZB:SQMW:BHSO:XK3J"
ERRO[9845] error authorizing context: invalid token      environment=development http.request.host=localhost:5000 http.request.id=9abaf613-1276-4338-b1b7-ea531dd668d9 http.request.method=GET http.request.remoteaddr=172.*.*.*:50655 http.request.uri=/v2/ http.request.useragent=docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-48-generic os/linux arch/amd64 instance.id=f785d636-e7bf-492b-9e62-8a6c329c4e73 service=registry version=v2.0.0-179-g3073b1d.m
INFO[9845] response completed                            environment=development http.request.host=localhost:5000 http.request.id=9abaf613-1276-4338-b1b7-ea531dd668d9 http.request.method=GET http.request.remoteaddr=172.*.*.*:50655 http.request.uri=/v2/ http.request.useragent=docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-48-generic os/linux arch/amd64 http.response.contenttype=application/json; charset=utf-8 http.response.duration=8.483406ms http.response.status=401 http.response.written=114 instance.id=f785d636-e7bf-492b-9e62-8a6c329c4e73 service=registry version=v2.0.0-179-g3073b1d.m
172.*.*.* - - [03/Jun/2015:05:27:41 +0000] "GET /v2/ HTTP/1.1" 401 114 "" "docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-48-generic os/linux arch/amd64"
</code></pre>
Auth server container's log:
<pre><code>
2015/06/01 09:18:37 http: TLS handshake error from 172.*.*.*:40167: remote error: unknown certificate authority
E0602 12:23:48.355771       1 server.go:174] {:@172.*.*.*:54625 test   }: wrong password
</code></pre>
TLS handshake fail. The certificate and private key is generated from 
<pre><code>openssl req -newkey rsa:2048 -nodes -keyout registry_auth.key -x509 -days 365 -out registry_auth.crt</code></pre>
The password for account 'test' is 'test'.

**Comment by rojer** [comment]
you need to figure out your certs situation, as neither registry nor auth
service trust one another.

there are two ways certs are used: one is for TLS session setup, the other
is to sign the token. it looks like you managed to get TLS going (so
registry did get the token back), but it doesn't trust the cert it was
signed with. setting auth.token.rootcertbundle = registry_auth.crt *should*
do the trick.

**Comment by summerQLin** [comment]
I've already added 'rootcertbundle'  for registry's config.yml.
<pre><code>
auth:
    token:
        realm: https://127.0.0.1:5001/auth
        service: Dockerregistry
        issuer: Acmeauthserver
        rootcertbundle: /go/src/github.com/docker/distribution/auth_cert/registry_auth.crt
</code></pre>

**Comment by rojer** [comment]
in my setup i have a separate CA cert configured system-wide, but i just
tried your setup and it works for me.
i used the exact command you posted to generate cert and key, configured it
under server.{certificate,key} for docker_auth, set rootcertbundle =
registry_auth.crt for the registry and it works.

**Comment by rojer** [comment]
closing as WFM.
