### ISSUE TITLE
Google Oauth: Docker login fails because because of invalid char in user name

### ISSUE THREAD

**Issue by jbruggem** [cesanta/docker_auth#30]
Hi, and first of all thanks for this cool project !

I'm trying to setup docker_auth with a google apps domain. I can start the auth service fine, and logging in the auth service goes well. It then tells me to run `docker login` with my e-mail address as username and a generated string as password.

When I do so, I get the following error from docker:

```bash
$ docker login
Username: [email-address]
Password: 
Email: 
Error response from daemon: Registration: "Wrong username format (it has to match \"^[a-z0-9]{4,30}$\")"
```

Am I doing something wrong ?

**Comment by rojer** [comment]
you are logging into docker hub.
add your registry address to the docker login command
