### ISSUE TITLE
Unable to push new images after adding auth

### ISSUE THREAD

**Issue by djenriquez** [cesanta/docker_auth#31]
Hello,

I added authentication to my private registry and now am unable to push new images. Oddly enough, pulling images and pushing UNCHANGED images work fine.

However, when I push a new image, or an image that requires any layers to be updated, I get this:
```
bash-3.2$ docker push docker.djsdomain.com/gleaner
The push refers to a repository [docker.djsdomain.com/gleaner] (len: 1)
c2dce7213213: Pushing [==================================================>]     32 B/32 B
unauthorized: access to the requested resource is not authorized
```

Logs from the authentication server for this transaction:
```
I0930 00:47:27.582009       1 server.go:220] Auth request: {djenriquez:***@10.170.140.121:37572 {djenriquez pull,push repository gleaner}}
I0930 00:47:27.586096       1 server.go:103] Authn static djenriquez -> true, %!s(<nil>)
I0930 00:47:27.586165       1 acl.go:37] {djenriquez pull,push repository gleaner} matched {"Match":{"account":"djenriquez"},"Actions":["*"]}
I0930 00:47:27.586436       1 server.go:122] Authz static ACL {djenriquez pull,push repository gleaner} -> [pull push], %!s(<nil>)
I0930 00:47:27.595800       1 server.go:184] New token for {djenriquez:***@10.170.140.121:37572 {djenriquez pull,push repository gleaner}}: {"iss":"djsdomain ACME server","sub":"djenriquez","aud":"Docker Registry","exp":1443574947,"nbf":1443574046,"iat":1443574047,"jti":"6833611524882594851","access":[{"type":"repository","name":"gleaner","actions":["pull","push"]}]}
I0930 00:47:27.595879       1 server.go:250] {"token":"<Removing token for security -DJ>"}
```

I think the authentication server is doing everything correctly, but I figured i'd check if anything here looks odd. I do know that before adding authentication, I was able to push new images just fine.

I also opened an issue in the official [docker/distribution](https://github.com/docker/distribution/issues/1043) repo.

Any ideas?

**Comment by rojer** [comment]
yes, to me this also looks like auth server has issued a token that includes push action, so registry should allow push.
please verify that `issuer` in the registry config matches issuer configured in the auth server, namely that it is set to `issuer: "djsdomain ACME server"`.
other than that i have no ideas, please re-open if you determine this to be auth server issue.
