### ISSUE TITLE
Please rebuild with recent ca-certificates

### ISSUE THREAD

**Issue by rck** [cesanta/docker_auth#320]
On 1st of October I noticed that external auth stopped working. Our external auth is a simple Go program that connects to a server via https that has a let's encrypt certificate. Might be related to this? https://community.letsencrypt.org/t/transition-to-isrgs-root-delayed-until-jan-11-2021/125516 . But anyways, replacing the `ca-certificates.crt` with one from recent Alpine fixed it. Would be great if you could rebuild the image.

**Comment by techknowlogick** [comment]
Thanks for ping, I've sent a rebuild of the docker container.

Which image are you using? I may need to re-tag if you aren't using the `:edge` tag.

**Comment by techknowlogick** [comment]
I've just tagged a new version which hopefully fixes things. I will close this now. Please re-open if you still experience issues :)

**Comment by rck** [comment]
> Which image are you using?

The `:1` which looks like it was pushed. So thanks for fixing.
