### ISSUE TITLE
Handler for POST /auth returned error: no successful auth challenge for <myserver:5000/v2/

### ISSUE THREAD

**Issue by jc-evogi** [cesanta/docker_auth#33]
Hi All,
I'm needing your help to understand why the authorization server setup  is not working for us. I am using Docker 1.8.2 and trying to integrate Cesanta's authorization server with Docker Registry (v.2.1.1) . For this integration purpose I am using the following reference  http://the.binbashtheory.com/creating-private-docker-registry-2-0-with-token-authentication-service/.  For authentication I am using exactly the same "authorize_config.yml" described in the link of course replacing  the htpasswd  password accordingly. Unfortunately   I am getting always this error ..."Error response from daemon: no successful auth challenge for http://docker-myserver.com:5000/v2/ - errors: [token auth attempt for registry http://docker-myserver.com:5000/v2/: https://myserver.com:5001/auth?account=admin&service=Docker+registry request failed with status: 401 Unauthorized].  In the Authorization server log I can't see any message. Please let me know if you have any suggestion or need more information regarding to my setup.

Command used
$ docker login  docker-myserver.com:5000

Launching Docker Registry:
docker run -d -p 5000:5000 \
  --restart="always" --name "registrytoken" \
  -v `pwd`/config.yml:/etc/docker/registry/config.yml \
  -v /root/auth_server/ssl:/ssl \
  -v /root/docker_registry/data:/var/lib/registry \
  -e "REGISTRY_AUTH=token" \
  -e "REGISTRY_AUTH_TOKEN_REALM=https://docker-myserver.com:5001/auth" \
  -e "REGISTRY_AUTH_TOKEN_SERVICE=Docker registry" \
  -e "REGISTRY_AUTH_TOKEN_ISSUER=Auth Service" \
  -e "REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/ssl/server.pem" \
  -v /root/auth_server/ssl:/ssl \
   registry:2.1.1 

Launching Authorization Server:
 docker run -d --name docker_auth -p 5001:5001 \
-v `pwd`/auth_server/config:/config:ro \
-v /var/log/docker_auth:/logs \
--restart=always \
-v `pwd`/auth_server/ssl:/ssl cesanta/docker_auth /config/auth_config.yml

Thanks in advance 

JC

**Comment by rojer** [comment]
"In the Authorization server log I can't see any message" - they should be in /var/log/docker_auth. is there really nothing there?

**Comment by jc-evogi** [comment]
Hi Rojer,
Thanks for your answer. We really like your product's concept and would like to see that working in our side. 
After a fail docker login session I double checked the authorization server's container and there is not files in  "/logs" directory and neither in the host "/var/log/docker_auth" directory.   Tried a quick validation of "docker run" with those 2 flags that you mentioned and they are not working as expected, I don't know if that has something to do with the docker v1.8.2 that I am using. These are my results now including those flags that you mentioned:

# docker run -d -p 5001:5001 cesanta/docker_auth --v=2 --alsologtostderr /config/auth_config.yml

CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS                     PORTS                    NAMES
0a6a47e5a93f        cesanta/docker_auth   "/auth_server --v=2 -"   4 seconds ago       Exited (1) 3 seconds ago                            condescending_tesla

 
NOTE: At the beginning it looks like the container launch but not really as you see the status is "EXITED (1) 3 seconds ago". Now if I insert the 2 flags in the Auth. Server "docker run" in sequence referred in my report I am getting different error. For Example:

$ docker run -d --name docker_auth -p 5001:5001 --v=2 --alsologtostderr -v pwd/auth_server/config:/config:ro -v /var/log/docker_auth:/logs --restart=always -v pwd/auth_server/ssl:/ssl cesanta/docker_auth /config/auth_config.yml
flag provided but not defined: --v
See 'docker run --help'.

I will look forward for your comments,

Thanks in advance,

JC

**Comment by rojer** [comment]
sorry, you're doing something wrong but i don't have time to troubleshoot.
