### ISSUE TITLE
How to develop a docker_auth

### ISSUE THREAD

**Issue by coocla** [cesanta/docker_auth#35]
Hi:
    I would like to use keystone as the authentication medium, using Python as the development language, which I should follow the standards?
    For example, the API structure specification and return specification。
    Thank you.

**Comment by rojer** [comment]
i'm sorry to say that developing in python is not supported and will not be in the near future. you need to use Go. a quick google search for <golang keystone authentication> brought up a couple of what looks like keystone client libraries, i suggest you use those to implement the Authenticator interface (https://github.com/cesanta/docker_auth/blob/master/auth_server/authn/authn.go#L22).

**Comment by coocla** [comment]
I think as long as the same function can HTTP API v2 work with registry. Is not limited to the back-end development language now. I need to develop their own to implement custom interior, but I'm not good golfing. I am eager to get this HTTP API specification document developed.
