### ISSUE TITLE
Update Base Image to alpine 3.17

### ISSUE THREAD

**Issue by HouseLarry** [cesanta/docker_auth#357]
Any chance we could get a newer build of the currently released code on alpine 3.17 pushed out to docker hub?  It looks like the current 1.10 was built on top of 3.14.  I updated the current docker file in the repo to 3.17 (it's currently set to 3.19 which fails) and have pushed it into a test environment where it has been running happily for a few weeks now.

Thoughts?
Thanks!

**Comment by techknowlogick** [comment]
Thanks for the suggestion. I've sent a PR to update this.

**Comment by DotNet-Ninja** [comment]
Thanks for updating this so quickly!
