### ISSUE TITLE
Error when compile it

### ISSUE THREAD

**Issue by ckmm** [cesanta/docker_auth#36]
Hi,

I'm trying to compile the server go. But i have problem. I make it and when run the "go build" show:

root@a235c66bb404:~/docker_auth/auth_server# go build                           
main.go:29:2: cannot find package "github.com/cesanta/docker_auth/auth_server/se
rver" in any of:                                                                
        /usr/local/go/src/github.com/cesanta/docker_auth/auth_server/server (fro
m $GOROOT)                                                                      
        /go/src/github.com/cesanta/docker_auth/auth_server/server (from $GOPATH)
main.go:30:2: cannot find package "github.com/facebookgo/httpdown" in any of:   
        /usr/local/go/src/github.com/facebookgo/httpdown (from $GOROOT)         
        /go/src/github.com/facebookgo/httpdown (from $GOPATH)                   
main.go:31:2: cannot find package "github.com/golang/glog" in any of:           
        /usr/local/go/src/github.com/golang/glog (from $GOROOT)                 
        /go/src/github.com/golang/glog (from $GOPATH)                           
main.go:32:2: cannot find package "gopkg.in/fsnotify.v1" in any of:             
        /usr/local/go/src/gopkg.in/fsnotify.v1 (from $GOROOT)                   
        /go/src/gopkg.in/fsnotify.v1 (from $GOPATH)                             

Any idea to resolve it?

**Comment by rojer** [comment]
sorry, no. must be something about your go environment.

**Comment by lucasalcantara** [comment]
run go get ./... in your src
