### ISSUE TITLE
ldap auth - how to deal with binddn that expects account as email

### ISSUE THREAD

**Issue by rtvu** [cesanta/docker_auth#360]
My ldap server expects the user account to be an email address. These account names are not compatible with docker's username format. Is there a way to provide both email address and username to registry and have it authenticate with the appropriate values?

**Comment by zapp42** [comment]
Can't you just hard-code the email domain and append it to ${account}?

**Comment by rtvu** [comment]
Ohh, I didn't think about. Thanks.

**Comment by rtvu** [comment]
Feature can be accomplished with hard coding email domain.
