### ISSUE TITLE
docker run gives me "no such file or directory" for the config file

### ISSUE THREAD

**Issue by DL3KB** [cesanta/docker_auth#368]
Hi there,
if I try to run the docker container it always exits with the following error. I've tried many things, changed the directory, tried the default file path, used different releases.

Failed to load config: could not read /root/reg_auth/auth_server.yml: open /root/reg_auth/auth_server.yml: no such file or directory

**Comment by techknowlogick** [comment]
Hello, thank you for opening this issue. Could you share the `docker run` command (or docker-compose file) that you used to run the service?

**Comment by DL3KB** [comment]
Here you go :)

"docker run --rm --name docker_auth -p 5001:5001 --network registry_network -v /root/reg_auth:/config:ro     cesanta/docker_auth:1 /root/reg_auth/auth_server.yml"

**Comment by techknowlogick** [comment]
I have some good news!
`-v /root/reg_auth:/config:ro` says that the `/root/reg_auth` directory will be found as `/config` inside the docker container. Which means you'll need to change `/root/reg_auth/auth_server.yml` to `/config/auth_server.yml` so the service inside the docker container can pick up the config :)

**Comment by DL3KB** [comment]
My mistake, sorry

**Comment by techknowlogick** [comment]
@DL3KB all good, glad we were able to solve it :)
