### ISSUE TITLE
Invalid Memory Address with AD LDAP via TLS

### ISSUE THREAD

**Issue by kidhasmoxy** [cesanta/docker_auth#37]
I've configured LDAP for TLS connecting to an AD server, but I get the following error whenever a user attempts to login.

runtime error: invalid memory address or nil pointer dereference
goroutine 12 [running]:
net/http.(*conn).serve.func1(0xc82017fce0, 0x7f2f7223a268, 0xc82008c840)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/go-ldap/ldap.(*Conn).StartTLS(0xc82027c900, 0xc8201c1680, 0x0, 0x0)
	/home/rojer/go/src/github.com/go-ldap/ldap/conn.go:180 +0x125c
github.com/cesanta/docker_auth/auth_server/authn.(*LDAPAuth).ldapConnection(0xc8200240b0, 0xc8201fe540, 0x0, 0x0)
	/home/rojer/go/src/github.com/cesanta/docker_auth/auth_server/authn/ldap_auth.go:133 +0x33d
github.com/cesanta/docker_auth/auth_server/authn.(*LDAPAuth).Authenticate(0xc8200240b0, 0xc8202748d2, 0xd, 0xc82027e32e, 0x9, 0x0, 0x0, 0x0)
	/home/rojer/go/src/github.com/cesanta/docker_auth/auth_server/authn/ldap_auth.go:56 +0x8c
github.com/cesanta/docker_auth/auth_server/server.(*AuthServer).Authenticate(0xc820126680, 0xc82025ed80, 0x11, 0x0, 0x0)
	/home/rojer/go/src/github.com/cesanta/docker_auth/auth_server/server/server.go:109 +0x11e
github.com/cesanta/docker_auth/auth_server/server.(*AuthServer).doAuth(0xc820126680, 0x7f2f7223e8e8, 0xc8202820b0, 0xc820233960)
	/home/rojer/go/src/github.com/cesanta/docker_auth/auth_server/server/server.go:229 +0x3d1
github.com/cesanta/docker_auth/auth_server/server.(*AuthServer).ServeHTTP(0xc820126680, 0x7f2f7223e8e8, 0xc8202820b0, 0xc820233960)
	/home/rojer/go/src/github.com/cesanta/docker_auth/auth_server/server/server.go:201 +0x1ef
net/http.serverHandler.ServeHTTP(0xc8201a05a0, 0x7f2f7223e8e8, 0xc8202820b0, 0xc820233960)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82017fce0)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6

**Comment by rojer** [comment]
i have no way to test it, unfortunately, we don't use LDAP, let alone with AD.
let's ask @summerQLin who wrote the LDAP plugin. any ideas?

**Comment by summerQLin** [comment]
@kidhasmoxy could you please paste your ldap_auth.yml configuration here?

**Comment by kidhasmoxy** [comment]
I can paste a redacted version, to start. Although, now that I look at this closer, I realize that we should be searching for sAMAccountName for AD. I'll try that to see if it helps. 

ldap_auth:
  addr: "my.public.domain:636"
  tls: true
  # In case bind DN and password is required for querying user information,
  # specify them here. Plain text password is read from the file.
  bind_dn: "CN=svc_ldap,OU=Service Accounts,OU=Managed Objects,DC=example,DC=DC=com"
  bind_password_file: "/config/ldap_pw"
  # User query settings. ${account} is expanded from auth request 
  base: "DC=example,DC=com"
  filter: "(&(uid=${account})(objectClass=person))"

**Comment by kidhasmoxy** [comment]
Still no go, as the error is happening at the StartTLS phase. I validated the connection information to LDAP with OpenLDAP client, so the content is correct. Is there an option of using DialTLS for testing? I haven't been able to put together an environment to recompile, or I would try it myself. 

I1027 22:16:53.307686       1 ldap_auth.go:126] Dial: starting...redacted.example.com:636
dockerauth_1 | I1027 22:16:53.511054       1 ldap_auth.go:132] StartTLS...
dockerauth_1 | I1027 22:17:03.603112       1 server.go:1934] http: panic serving redacted_ip:65026: runtime error: invalid memory address or nil pointer dereference
dockerauth_1 | goroutine 14 [running]:
dockerauth_1 | net/http.(*conn).serve.func1(0xc8203adc30, 0x7f9ba2166018, 0xc820095600)
dockerauth_1 | 	/usr/local/go/src/net/http/server.go:1287 +0xb5
dockerauth_1 | github.com/go-ldap/ldap.(*Conn).StartTLS(0xc82045b100, 0xc820470780, 0x0, 0x0)
dockerauth_1 | 	/home/rojer/go/src/github.com/go-ldap/ldap/conn.go:180 +0x125c
dockerauth_1 | github.com/cesanta/docker_auth/auth_server/authn.(*LDAPAuth).ldapConnection(0xc8200240b0, 0x9, 0x0, 0x0)
dockerauth_1 | 	/home/rojer/go/src/github.com/cesanta/docker_auth/auth_server/authn/ldap_auth.go:133 +0x33d
dockerauth_1 | github.com/cesanta/docker_auth/auth_server/authn.(*LDAPAuth).Authenticate(0xc8200240b0, 0xc82046cc12, 0xd, 0xc82046bd8e, 0x9, 0x0, 0x0, 0x0)
dockerauth_1 | 	/home/rojer/go/src/github.com/cesanta/docker_auth/auth_server/authn/ldap_auth.go:56 +0x8c
dockerauth_1 | github.com/cesanta/docker_auth/auth_server/server.(*AuthServer).Authenticate(0xc820126740, 0xc8204567e0, 0x11, 0x0, 0x0)
dockerauth_1 | 	/home/rojer/go/src/github.com/cesanta/docker_auth/auth_server/server/server.go:109 +0x11e
dockerauth_1 | github.com/cesanta/docker_auth/auth_server/server.(*AuthServer).doAuth(0xc820126740, 0x7f9ba216a880, 0xc820444dc0, 0xc820428a80)
dockerauth_1 | 	/home/rojer/go/src/github.com/cesanta/docker_auth/auth_server/server/server.go:229 +0x3d1
dockerauth_1 | github.com/cesanta/docker_auth/auth_server/server.(*AuthServer).ServeHTTP(0xc820126740, 0x7f9ba216a880, 0xc820444dc0, 0xc820428a80)
dockerauth_1 | 	/home/rojer/go/src/github.com/cesanta/docker_auth/auth_server/server/server.go:201 +0x1ef
dockerauth_1 | net/http.serverHandler.ServeHTTP(0xc8201a05a0, 0x7f9ba216a880, 0xc820444dc0, 0xc820428a80)
dockerauth_1 | 	/usr/local/go/src/net/http/server.go:1862 +0x19e
dockerauth_1 | net/http.(*conn).serve(0xc8203adc30)
dockerauth_1 | 	/usr/local/go/src/net/http/server.go:1361 +0xbee
dockerauth_1 | created by net/http.(*Server).Serve
dockerauth_1 | 	/usr/local/go/src/net/http/server.go:1910 +0x3f6

**Comment by kidhasmoxy** [comment]
I did some testing with the ruby net:ldap library and ran into a similar "connection reset by peer" issue when I used StartTLS. The connection was successful when I switched to using the "Simple_TLS" option. 

The setup we employ means that there's no LDAP connection available for our AD (I believe it's via Win Server 2008), and we only accept connections over LDAP/S. 

@summerQLin Would reverting to the DialTLS approach resolve the issue?

**Comment by summerQLin** [comment]
@kidhasmoxy, port 389 is not available for your AD, right? StartTLS should go with port 389, ldap:// not ldaps://. I will have TLS enabled.

**Comment by kidhasmoxy** [comment]
Exactly, 389 is filtered publicly by firewall, but instead require TLS from the start.

**Comment by akatrevorjay** [comment]
Yeah, I ran into this as well when trying to use LDAPS before looking in the code and realizing it's not yet supported (only TLS is at the moment).

**Comment by rojer** [comment]
I finished @summerQLin 's PR and pushed. :latest has the new code but I have not tested it - as i hsaid, i have no access to a LDAP server. if someone could report here, that'd help.

**Comment by julakali** [comment]
Using tls = always works for me (ldaps), but this will result in the following error:
authn #2 returned error: LDAP Result Code 200 "": tls: either ServerName or InsecureSkipVerify

Specifying insecure_tls_skip_verify=true will work, but i would rather like to be able to specify the ServerName :)

**Comment by summerQLin** [comment]
@julakali could you please try to add your ServerName here https://github.com/cesanta/docker_auth/blob/master/auth_server/authn/ldap_auth.go#L144
to have a test?
Change this line to be 
```
l, err = ldap.DialTLS("tcp", fmt.Sprintf("%s", la.config.Addr), &tls.Config{InsecureSkipVerify: la.config.InsecureTLSSkipVerify, ServerName: "your ldap server name"})
```
Please let me know your test result.

**Comment by dpetzel** [comment]
FWIW, I can confirm adding `ServerName` as suggested above did work for me.

**Comment by rojer** [comment]
@dpetzel can you send a PR? i'll merge it
