### ISSUE TITLE
Remove insecure cipher suites

### ISSUE THREAD

**Issue by stingshen** [cesanta/docker_auth#379]
[Golang tls package](https://github.com/golang/go/blob/release-branch.go1.21/src/crypto/tls/cipher_suites.go#L53) lists cipher suites excluding those with security issues. 

We may exclude those insecure cipher suites from [TLSCipherSuitesValues](https://github.com/cesanta/docker_auth/blob/main/auth_server/server/config.go#L94)?

**Comment by techknowlogick** [comment]
Thanks for the suggestion, would you be able to send a PR to align with the updated golang tls package list?

**Comment by stingshen** [comment]
> Thanks for the suggestion, would you be able to send a PR to align with the updated golang tls package list?

Sure, the PR is submitted
