### ISSUE TITLE
Question on API Access

### ISSUE THREAD

**Issue by silverbp** [cesanta/docker_auth#4]
I finally got this working, still having issues related to osx and boot2docker with custom CA but it works from one ubuntu box to another!! Great work!

One question though...
Is there a way to just get a token to pass with curl in order to hit docker registry api?

**Comment by rojer** [comment]
yes, there is:

$ curl --cacert /path/to/ca.crt -d 'account=USER&service=my_service&scope=repository:hello-world:pull' -u USER https://docker.example.com:5001/
Enter host password for user 'USER':
{"token":"eyJ0.....yQ"}

you can read the spec (https://github.com/docker/distribution/blob/master/docs/spec/auth/token.md) about scope and account, but basically scope is repostory:REPO_NAME:ACTIONS
REPO_NAME is what is some times called image name (i.e. the thing you docker pull), and ACTIONS is push, pull or both (i.e. "push,pull"). note that docker registry requests both push and pull actions for "docker push".
if you get access denied, either the password is wrong or the request (account, service, scope) did not match the acls (or matched one that disallows one of the request actions).
to debug, increase verbosity (--v=1 or --v=2 for even more details).

**Comment by rojer** [comment]
and to use it to talk to the registry:

$ curl --cacert /path/to/ca.crt -H 'Authorization: bearer eyJ0.....yQ' https://docker.example.com:5000/v2/
{}

**Comment by silverbp** [comment]
Perfect thanks!!

**Comment by silverbp** [comment]
A couple things now that I'm finally getting around to this..

if you go into your ~/.docker/config.json file and pull out the value for "auth", then base64 decode it you can pass it into curl like this:

curl -v --user {base64decodedtextfromabove} -d 'account={username}&service=registry&scope=repository:{imagename}:pull,push' https://{registry_server_url}/auth

don't forget the forward slash auth at the end of the url, but the above would get you a push/pull token for the imagename you are requesting if you have the access. If you don't, it will give you a token for what you have access to.
