### ISSUE TITLE
When creating a token, 'not before' is really necessary?

### ISSUE THREAD

**Issue by shyr** [cesanta/docker_auth#41]
If the time of running this server (for example, my local PC) is different with time of docker registry (on IDC), token will be failed to verify, because of nbf(not before) in claim.
To be specific, when the time of docker_auth is faster than that of docker registry, we should wait to verify a token as the gap.

By the way, `nbf` field can get away. It's optional (https://tools.ietf.org/html/rfc7519#page-10)
So.. In my opinion, it is better to get away of it.

**Comment by shyr** [comment]
Anyway, It was very time-consuming to figuring out this problem. T^T
I hope others not spend time with it.

**Comment by rojer** [comment]
working as intended. we allow 1 second of difference (we set nbf = now - 1), but beyond that, please make sure your clock is synced, use NTP.
