### ISSUE TITLE
Using {account} variable in ACLs and Oauth

### ISSUE THREAD

**Issue by corepb** [cesanta/docker_auth#45]
Hello everyone!

When I am trying to use a match like:
{account: "/.+/", name: "${account}/*"}

and when I want to use it together with google_auth I am having such an issue:

root@dockercli:~# docker tag a5a467fddcb8 registry.somedomain.org/corepb@somedomain.com/ubuntu-test
FATA[0000] Error response from daemon: Illegal tag name (somedomain.com/ubuntu-test): only [A-Za-z0-9_.-] are allowed, minimum 1, maximum 128 in length

and I can't push it anyhow to registry. To be able to push it I have to include my full e-mail to registry path.

Thanks for great project and I would appreciate your help.

**Comment by rojer** [comment]
this doesn't seem like auth server error to me.

the error seems pretty clear: tag name is illegal

**Comment by corepb** [comment]
I agree rojer, more like a feature request.


So currently (when using Google auth) I can use variable {account} which is equal to someaccount@somedomain.com.

It would be really nice to have {account_prefix} which would be 'someaccount'.

Then something like:

docker tag a5a467fddcb8 registry.somedomain.org/corepb/ubuntu-test
docker push registry.somedomain.org/corepb/ubuntu-test

would be possible.

What do you think?

**Comment by rojer** [comment]
ah, i see, that's what you mean... ok. let me think about it.

**Comment by corepb** [comment]
Thanks rojer!

**Comment by rojer** [comment]
i don't want to introduce a special variable, but supporting capture groups would work.
something like this:
`{account: "/^([^@]+).*/", name: "${account:1}/*"}`
`${account:N}` would reference capture group `N` obtained when matching `account`.

can you code it yourself? i'd take a PR that implements that. if not, then i'm afraid you'll have to wait until i have some spare time, for which i cannot make any promises...

**Comment by pandada8** [comment]
any update ?

**Comment by pandada8** [comment]
Hey, I have a patch in #124 implement the capture group replacement. Can @rojer merge that ?
