### ISSUE TITLE
can not build it by Makefile

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [cesanta/docker_auth#51]
root@ubuntu-zxc:/home/docker_auth/auth_server# make
go get -v  -u  github.com/tools/godep github.com/jteeuwen/go-bindata/... .
github.com/tools/godep (download)
github.com/jteeuwen/go-bindata (download)
Fetching https://_/home/docker_auth/auth_server?go-get=1
https fetch failed.
Fetching http://_/home/docker_auth/auth_server?go-get=1
import "_/home/docker_auth/auth_server": http/https fetch for import "_/home/docker_auth/auth_server": Get http://_/home/docker_auth/auth_server?go-get=1: lookup _: no such host
package github.com/tools/godep
	imports github.com/tools/godep/Godeps/_workspace/src/github.com/kr/fs
	imports github.com/tools/godep/Godeps/_workspace/src/github.com/kr/pretty
	imports github.com/tools/godep/Godeps/_workspace/src/github.com/kr/text
	imports github.com/tools/godep/Godeps/_workspace/src/github.com/pmezard/go-difflib/difflib
	imports github.com/tools/godep/Godeps/_workspace/src/golang.org/x/tools/go/vcs
	imports github.com/jteeuwen/go-bindata
	imports github.com/jteeuwen/go-bindata/go-bindata
	imports _/home/docker_auth/auth_server: unrecognized import path "_/home/docker_auth/auth_server"
make: *** [update-deps] Error 1

**Comment by SydOps** [comment]
@zhengxiaochuan-3 

Try with below steps:
```
mkdir -p /home/docker_auth/go/src/github.com/cesanta
export GOPATH=/home/docker_auth/go
export GOBIN=$GOPATH/bin
export PATH=$GOPATH:$GOBIN:$PATH
cd  /home/docker_auth/go/src/github.com/cesanta
git clone https://github.com/cesanta/docker_auth.git
cd docker_auth
make
```

Let me know if you got any progresses.

**Comment by rojer** [comment]
thanks, Bill.
yes, you need a properly set up Go environment.

**Comment by SydOps** [comment]
@rojer 

I can generate `auth_server` with command `go build`. 
```
ubuntu@ip-172-31-6-102:~/go/src/github.com/cesanta/docker_auth/auth_server$ go build
ubuntu@ip-172-31-6-102:~/go/src/github.com/cesanta/docker_auth/auth_server$ ls -l auth_server
-rwxr-xr-x 1 ubuntu ubuntu 13090992 Dec  8 11:58 auth_server
```
But when I run `make`, I still have issues:
```
ubuntu@ip-172-31-6-102:~/go/src/github.com/cesanta/docker_auth/auth_server$ make
go get -v -u -f github.com/tools/godep github.com/jteeuwen/go-bindata/... .
github.com/tools/godep (download)
github.com/jteeuwen/go-bindata (download)
github.com/cesanta/docker_auth (download)
github.com/dchest/uniuri (download)
github.com/go-ldap/ldap (download)
gopkg.in/asn1-ber.v1 (download)
github.com/golang/glog (download)
github.com/syndtr/goleveldb (download)
github.com/golang/snappy (download)
golang.org/x/crypto (download)
github.com/deckarep/golang-set (download)
gopkg.in/mgo.v2 (download)
github.com/docker/distribution (download)
github.com/Sirupsen/logrus (download)
github.com/gorilla/mux (download)
github.com/gorilla/context (download)
golang.org/x/net (download)
github.com/docker/libtrust (download)
gopkg.in/yaml.v2 (download)
github.com/facebookgo/httpdown (download)
github.com/facebookgo/clock (download)
github.com/facebookgo/stats (download)
gopkg.in/fsnotify.v1 (download)
godep save
godep: cannot find package "golang.org/x/sys/unix" in any of:
	/usr/lib/go/src/golang.org/x/sys/unix (from $GOROOT)
	/home/ubuntu/go/src/golang.org/x/sys/unix (from $GOPATH)
Makefile:20: recipe for target 'godep' failed
make: *** [godep] Error 1
ubuntu@ip-172-31-6-102:~/go/src/github.com/cesanta/docker_auth/auth_server$
```
What did I miss?

**Comment by scatat** [comment]
So I don't know if you got round this or not ( I suspect you did :) ) - but the solution is documented here: https://github.com/tools/godep/issues/377
More specifically, one needs to run "go get golang.org/x/sys/unix" manually.

Beng a Go newbie, I struggled with deps not being found until I set up my workspace as per: https://golang.org/doc/code.html  - ie:
- Set up the dir structure as detailed above ( eg in my case, the workspace root was /usr/local/src/go and the git clone was done so that the path to the repo was: usr/local/src/go/src/github.com/cesanta/docker_auth )
- Set up the GOPATH and GOBIN env vars correctly to point at the root of the workspace ( eg in my case, export GOPATH=/usr/local/src/go ; export GOBIN=$GOPATH/bin )
