### ISSUE TITLE
Not able to search images with "docker search"

### ISSUE THREAD

**Issue by tmuesele** [cesanta/docker_auth#52]
Hi everyone,

I set up the auth. server and it is working really well with the pull/push requests.
The only missing part is the "docker search" part.
I added my private registry in the docker config (--add-registry) but I'm not able to run the search.

I can see this error-message with every search-request in the registry-logs:
registry_1 | time="2015-12-08T14:29:59Z" level=warning msg="error authorizing context: authorization token required"

Any hint from your side?
Thanks in advance!

**Comment by rojer** [comment]
sorry, no idea. if you think this is related to auth, you'll need to provide more info.
