### ISSUE TITLE
Error 400 OAuth 2.0

### ISSUE THREAD

**Issue by Sylvaindce** [cesanta/docker_auth#53]
Hi, 
I'm working to deploy a google auth for a private registry with your docker_auth and after configuration the Static user works perfectly but when i try to use Google Auth, it tell me error 400.

Any Idea?
![error](https://cloud.githubusercontent.com/assets/12686429/11865922/b36f1dbe-a4a7-11e5-8ac7-056eaf35cbd9.png)

Thanks in advance

**Comment by rojer** [comment]
google auth is a bit finicky and 400 doesn't give much diagnostic.
make sure you're using the right client id and that it's configured properly.
fwiw, here's how mine is configured
![oauth client docker login](https://cloud.githubusercontent.com/assets/531307/11749603/ae97cbe0-a026-11e5-9215-0768ff37263f.png)

**Comment by Sylvaindce** [comment]
Thanks for your answer, I have the same configuration but i guess it didn't work with local address.

For me after https://localhost:5001
it https://10.10.0.101:5001

Have you ever tried with local address ?

**Comment by Sylvaindce** [comment]
Like that
![console](https://cloud.githubusercontent.com/assets/12686429/11865865/39bcb97c-a4a7-11e5-99a2-f607f92f8d0a.jpg)

**Comment by techknowlogick** [comment]
Closing as unable to replicate. Please re-open if you continue to experience this.
