### ISSUE TITLE
Bad regex pattern from mongo shuts the entire server down

### ISSUE THREAD

**Issue by carsonoid** [cesanta/docker_auth#58]
I am running several instances of the auth server in production and I need to acl fetching to be more robust. Right now one bad acl entry will shut the entire server until manually restarted.  Ideally bad rules will simply be ignored and the rest of the ACLs will continue to load. I'm happy and ready to write the code myself but I want your input on policy before I do anything. Maybe we could have a optional error collection in mongo where we can stick reports of failed ACL loads? I want to do something besides silently fail and crash the server.  This was/is not an issue when using hard coded acls but is quickly becoming a problem when using mongo to back everything. 

BTW thanks for the otherwise great little server!

**Comment by rojer** [comment]
is failure to start what you see, or do you see it crashing when reloading? that is not supposed to happen, if it does, i'd like to see the stack trace.

the intended behavior is for the server to fail to start if ACL entries cannot be parsed, but if an entry has been added while it was running, it will refuse to load config.

i don't think simply ignoring acl entries is a good idea.

**Comment by carsonoid** [comment]
18:23:25.178534       1 main.go:43] Config from /auth_config.yml (2 users, 3 ACL static entries)
18:23:25.178578       1 acl.go:89] Created ACL Authorizer with 3 entries
18:23:25.179243       1 mgo_session.go:64] Creating MongoDB session (operation timeout 10s)
18:23:25.184895       1 acl_mongo.go:136] Number of new ACL entries from MongoDB: 6
18:23:25.184915       1 main.go:46] Failed to create auth server: entry 2, invalid match conditions: invalid pattern "/!(/": invalid regex pattern: error parsing regexp: missing closing ): `!(`

Here is the stack trace. I get it when the server is starting and when I add the bad regex to mongo while the server is running. 

This makes sense given that all the ACL refresher does is create a new static authorizer just like the server does on boot.  I'll be submitting a PR for the fix soon.

**Comment by rojer** [comment]
as i said above, this is the intended behavior: the server will fail to start if it cannot parse its ACLs.
how do you propose to fix this?

**Comment by carsonoid** [comment]
I'm sorry for wasting your time. I just realized that this was happening because of my particular configuration. I have a docker-compose container set running with the auth config file mounted host to container.  The crashes I've been seeing "while running" were actually do to the server *restarting* when I saved updates to the config file.  Upon further investigation I have found that the ACL handling is exactly as you describe and is perfectly fine. It will continue to use stale ACLs when it can't load new ones. You can go ahead and close this erroneous issue.

**Comment by rojer** [comment]
no problem, thanks!
