### ISSUE TITLE
Auth fails if auth container has newer time than the registry server

### ISSUE THREAD

**Issue by stevendborrelli** [cesanta/docker_auth#59]
We saw an issue where the auth server was about 30 seconds ahead of the registry server due to misconfigured ntp. This got us thinking that there could be an issue if the auth server is even a couple of seconds ahead of the registry server. Should there be a little bit of a window (say 5 seconds before)? 

`time="2015-12-29T19:50:55.842580115Z" level=error msg="token not to be used before 1451418688 or after 1451419589 - currently 1451418655" `

**Comment by rojer** [comment]
there is, and it's 1 second:

```NotBefore:  now - 1,```

keeping accurate time is both easy and important for security. make sure your ntp is set up correctly.
