### ISSUE TITLE
config reload

### ISSUE THREAD

**Issue by DarkDirk** [cesanta/docker_auth#6]
Is there a way to let the docker_auth reread the config file? Currently you need to restart the container if you changed the config file. I see the following options:
1. reload on file changed
2. reload every minute
3. reload on every request
4. reload on the call of special api route

It would be nice to have one of this options (toggleable via config) if your config is changed from an external program like a CLI or a webinterface.

**Comment by rojer** [comment]
there isn't a way right now, but adding one sounds reasonable.
as always, no ETA but eventually there will be a way. :)
