### ISSUE TITLE
Unable to authenticate - Error 404

### ISSUE THREAD

**Issue by bigfoot90** [cesanta/docker_auth#66]
I've deployed a private registry on ```my.domain.com:5000``` and docker auth on ```my.domain.com:5001```.

I'm now trying to login by ```docker login my.domain.com:5001``` but I'm facing with error:
```
Error response from daemon: Unexpected status code [404] : Not found
```

If I try to login to port ```5000``` instead I'm having
```
Error response from daemon: no successful auth challenge for https://my.domain.com:5000/v2/ - errors: []
```

**Comment by rojer** [comment]
you should indeed login to the main registry port, i.e. 5000.
registry will respond with auth URL for client to use to obtain ticket (which will be 5001).
please post your registry and auth server configs and logs.

**Comment by bigfoot90** [comment]
Thank you very much for you support, I've resolved.
