### ISSUE TITLE
Support requests for multiple scopes

### ISSUE THREAD

**Issue by erikswanson** [cesanta/docker_auth#67]
Per docker/docker#20387:

> 1.  cesanta/docker_auth only understands a single scope query parameter, and the docker engine is requesting push/pull for the repository you are pushing to and pull access for the repository you're mounting the blob from. This means you request both scopes and the auth server only returns a token with the single repository scope.
> 
> ...
> 
> I can address issue number 2 so that it immediately falls back to pushing the blob on auth failure, specifically for the case of a cross-repo push, but I'd recommend filing an issue with cesanta/docker_auth to support this workflow.

**Comment by rojer** [comment]
let's see... can you give me an example of a token request that is handled incorrectly?

**Comment by erikswanson** [comment]
My own logs have aged off (I had to fall back to a different form of auth), but my understanding is they'd look like this:

    GET https://myregistry.private/auth?service=myregistry.private&scope=repository:foo/my-app:pull,push&scope=repository:foo/my-otherapp:pull

**Comment by rojer** [comment]
i see. this should be easy to do. what is the actual use case for this? when does this happen?

**Comment by erikswanson** [comment]
Docker 1.10 has the ability to avoid pushing the same layer to different repositories. To do that, it needs push and pull rights on the target repository, and pull rights on the repository that is the source of the "mount".

This helps a *ton* in the case of several $platform applications that all use the same customized $platform docker image.

**Comment by rojer** [comment]
i see. as i said, it should be easy to do, but i'm super busy atm.
if you (or anyone else reading this) do it, please send a PR, otherwise i'm afraid this will have to wait a few days

**Comment by rojer** [comment]
@erikswanson i built and pushed `cesnat/docker_auth:scopes`, can you give it a go?

**Comment by erikswanson** [comment]
@rojer Sorry, I'm super-busy for the next few days and it's not trivial for me to roll back the emergency removal of token auth from my production registry/fallback to an awful nginx conditional basic auth bodge. (The lack of it was triggering a serious performance issue in Docker 1.10.1, making my push times way worse than with < Docker 1.10: When a "mount" failed due to token scope, it'd fall all the way back to re-uploading the layer, even if that layer was already uploaded for a different tag in the same repository.)

If nobody else is able to look at/validate this by mid-next week, I should definitely have time then.

**Comment by rojer** [comment]
so i just need docker 1.10, re-tag some image as a different one, push and i should see requests for multiple scopes, right?

**Comment by erikswanson** [comment]
A different repository (foo/bar vs foo/baz) within the same registry, yes.

**Comment by rojer** [comment]
installed docker 1.10, verified that multiple scope auth requests and cross-repo pushes now work
