### ISSUE TITLE
Make an ACL engine like the Authentication

### ISSUE THREAD

**Issue by devinsba** [cesanta/docker_auth#7]
Allow ACL to pluggable like the authentication currently is.

Ex:
* LDAP
* A database

This allows an organization to have non developer maintain this mapping. For instance with new hires or people leaving. Or new repos and new groups

I would be happy to take a shot at adding this if you are open to this type of feature. Certain implementations would also solve #6

**Comment by rojer** [comment]
yes, this sounds reasonable to me.

**Comment by rojer** [comment]
fixed by #23
