### ISSUE TITLE
question about start the image

### ISSUE THREAD

**Issue by joey-jihua** [cesanta/docker_auth#74]
i following the readme to try this, but i always get following error:
------------------------------------------------------------------------------------------------------------------------------
root@ubu89:/config# docker run     --rm -it --name docker_auth -p 5001:5001     -v /path/to/config_dir:/config:ro     -v /var/log/docker_auth:/logs     paasrepo.io:5000/docker_auth:latest --v=2 --alsologtostderr /config/auth_config.yml 
F0321 09:09:07.255478       1 main.go:167] Failed to load config: could not read /config/auth_config.yml: open /config/auth_config.yml: no such file or directory
-----------------------------------------------------------------------------------------------------------------------

i have created the config folder than auth_config.yml file.   what shall i do to solve it?

**Comment by tinytub** [comment]
@joey-jihua 
`-v /path/to/config_dir:/config:ro` this part of option means you should put your auth_config.yml in "/path/to/config_dir" (the path in your host),and it will mount this path to "/config" in you container.

I guess you only put the auth_config.yml in your host /config path not in "/path/to/config_dir" on your host

maybe you should learn more about docker's options.

**Comment by rojer** [comment]
thanks @tinytub
