### ISSUE TITLE
[Proposal] : Parameterize the NotBefore validity of token for NTP sync issues more than 1 sec

### ISSUE THREAD

**Issue by gauravbhandare** [cesanta/docker_auth#75]
I am using docker auth and has been working fine. Lately with AWS multi AZ setup and cross AZ load balancing, we observed that the time on the hosts was not in sync to the sec. 

I understand from #41 and #59 that NotBefore flag cannot be made optional, however can we make the hardcoded 1 sec value optional/configurable from the config yaml file.

This will certainly help users like us where we are getting this issue despite the ntp configuration.
I have already tested the same from my fork and will generate the pull request shortly.

Please let me know your thoughts.

**Comment by rojer** [comment]
so, what value would you use? would, say, 3 seconds be enough? in that case we can just change the value.

**Comment by gauravbhandare** [comment]
In my case it was 8 secs. I am thinking having it configurable will allow users to decide. I have generated a pull request keeping default as 1. I can put an upper limit as well if you feel. But i guess keeping it us to user will help.

**Comment by mv012004** [comment]
+1, think this should be parametrized, so that it is flexible for people to use as is.

**Comment by rojer** [comment]
8 seconds? this really doesn't sound right. properly working NTP should not get _that_ far out of sync.
1 might be too tight, that's true.

let me think about it. we need to balance flexibility with proliferation of knobs.

**Comment by rojer** [comment]
in my experience, a machine with properly configured NTP will not get off by whopping 8 seconds, this just doesn't happen, unless the machine's RTC is misbehaving. it also sometimes happens after boot, when a machine that's been long off comes back. but in that case ntpdate during boot should bring it in sync before starting services.

so, i don't think we need a knob to control this.

that said, i'm willing to relax the threshold to 10 seconds, which should be more than enough. feel free to send me a PR to do that.

**Comment by gauravbhandare** [comment]
Submitted PR #76 for this.

**Comment by rojer** [comment]
i see, but it does more than i'm willing to accept. please squash it to one commit and leave just the 1 -> 10 seconds change.

**Comment by gauravbhandare** [comment]
Thanks for merging....One last question....when can we have the new image pushed to docker hub.

**Comment by rojer** [comment]
built and pushed to latest, will let it soak there for a few days before pushing to stable
