### ISSUE TITLE
UNAUTHORIZED when visit via browser

### ISSUE THREAD

**Issue by joey-jihua** [cesanta/docker_auth#77]
---------------------------------
docker_auth and registry were up successfully. but when i try to visit the registry by chrome, i get follwing error, is this work with registry version 2.3.1? 

error info:
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Name":"catalog","Action":"*"}]}]}

-the container's log as following: 

root@ubu89:/var/lib/docker/containers/2c3cdb37bb770574860623cb4e8bac1c90ce12d087338478260c5164e3ef395f# cat 2c3cdb37bb770574860623cb4e8bac1c90ce12d087338478260c5164e3ef395f-json.log 
{"log":"time=\"2016-03-22T08:28:48Z\" level=warning msg=\"No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable.\" go.version=go1.5.3 instance.id=1dbd103a-8580-45f4-9783-b11040c376ca version=v2.3.1 \n","stream":"stdout","time":"2016-03-22T08:28:48.184011866Z"}
{"log":"time=\"2016-03-22T08:28:48Z\" level=info msg=\"redis not configured\" go.version=go1.5.3 instance.id=1dbd103a-8580-45f4-9783-b11040c376ca version=v2.3.1 \n","stream":"stdout","time":"2016-03-22T08:28:48.184337501Z"}
{"log":"time=\"2016-03-22T08:28:48Z\" level=info msg=\"Starting upload purge in 35m0s\" go.version=go1.5.3 instance.id=1dbd103a-8580-45f4-9783-b11040c376ca version=v2.3.1 \n","stream":"stdout","time":"2016-03-22T08:28:48.184922941Z"}
{"log":"time=\"2016-03-22T08:28:48Z\" level=info msg=\"using inmemory blob descriptor cache\" go.version=go1.5.3 instance.id=1dbd103a-8580-45f4-9783-b11040c376ca version=v2.3.1 \n","stream":"stdout","time":"2016-03-22T08:28:48.186249676Z"}
{"log":"time=\"2016-03-22T08:28:48Z\" level=info msg=\"listening on [::]:5000\" go.version=go1.5.3 instance.id=1dbd103a-8580-45f4-9783-b11040c376ca version=v2.3.1 \n","stream":"stdout","time":"2016-03-22T08:28:48.187164777Z"}
{"log":"time=\"2016-03-22T08:29:21Z\" level=warning msg=\"error authorizing context: authorization token required\" go.version=go1.5.3 http.request.host=\"10.62.99.89:5000\" http.request.id=aa394ded-3de7-4b22-901a-eecddde06849 http.request.method=GET http.request.remoteaddr=\"10.60.69.15:51293\" http.request.uri=\"/v2/_catalog\" http.request.useragent=\"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36\" instance.id=1dbd103a-8580-45f4-9783-b11040c376ca version=v2.3.1 \n","stream":"stdout","time":"2016-03-22T08:29:21.355424343Z"}
{"log":"10.60.69.15 - - [22/Mar/2016:08:29:21 +0000] \"GET /v2/_catalog HTTP/1.1\" 401 134 \"\" \"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36\"\n","stream":"stdout","time":"2016-03-22T08:29:21.355636089Z"}
{"log":"time=\"2016-03-22T08:33:44Z\" level=warning msg=\"error authorizing context: authorization token required\" go.version=go1.5.3 http.request.host=\"10.62.99.89:5000\" http.request.id=505a6a57-d4dd-45cd-a39d-96d8c5a38e2d http.request.method=GET http.request.remoteaddr=\"10.60.69.15:51293\" http.request.uri=\"/v2/_catalog\" http.request.useragent=\"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36\" instance.id=1dbd103a-8580-45f4-9783-b11040c376ca version=v2.3.1 \n","stream":"stdout","time":"2016-03-22T08:33:44.62841023Z"}
{"log":"10.60.69.15 - - [22/Mar/2016:08:33:44 +0000] \"GET /v2/_catalog HTTP/1.1\" 401 134 \"\" \"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36\"\n","stream":"stdout","time":"2016-03-22T08:33:44.62897301Z"}
root@ubu89:/var/lib/docker/containers/2c3cdb37bb770574860623cb4e8bac1c90ce12d087338478260c5164e3ef395f#

**Comment by rojer** [comment]
and why exactly are you trying to use browser with it? what do you expect to happen?

**Comment by joey-jihua** [comment]
@rojer   i want to see if the registry work or not.  i also try to push image and  docker login, all failed 

root@ubu89:~# docker push registry.example.com:5000/hello-world
The push refers to a repository [registry.example.com:5000/hello-world]
unable to ping registry endpoint https://registry.example.com:5000/v0/
v2 ping attempt failed with error: Get https://registry.example.com:5000/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://registry.example.com:5000/v1/_ping: tls: oversized record received with length 20527
root@ubu89:~# docker login registry.example.com:5000
Username: admin
Password: 
Email: test^H
Error response from daemon: invalid registry endpoint https://registry.example.com:5000/v0/: unable to ping registry endpoint https://registry.example.com:5000/v0/
v2 ping attempt failed with error: Get https://registry.example.com:5000/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://registry.example.com:5000/v1/_ping: tls: oversized record received with length 20527. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry registry.example.com:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/registry.example.com:5000/ca.crt
root@ubu89:~#

**Comment by rojer** [comment]
i never tested with a browser, so i don't know if it's supposed to work or not.
docker login - yes.
try running the auth server with --v=2 and see what happens to the requests.

**Comment by joey-jihua** [comment]
i have put this option when i start up the docker auth.   
my docker version is 1.10.3  and the registry is 2.3.1

the docker docker auth container only output following informations: 
-----------------------------------------------------------------------------------------------
root@ubu89:/var/lib/docker/containers/1ed27c7f0d22817a6a331b8e05fad447888988987ed07e2f873b534576d9ec10# cat 1ed27c7f0d22817a6a331b8e05fad447888988987ed07e2f873b534576d9ec10-json.log 
{"log":"I0322 08:28:08.009895       1 main.go:43] Config from /config/auth_config.yml (3 users, 5 ACL static entries)\n","stream":"stderr","time":"2016-03-22T08:28:08.010406346Z"}
{"log":"I0322 08:28:08.010712       1 acl.go:89] Created ACL Authorizer with 5 entries\n","stream":"stderr","time":"2016-03-22T08:28:08.011015417Z"}
{"log":"I0322 08:28:08.010768       1 main.go:71] Cert file: /ssl/server.pem\n","stream":"stderr","time":"2016-03-22T08:28:08.011048379Z"}
{"log":"I0322 08:28:08.010780       1 main.go:72] Key file : /ssl/server.key\n","stream":"stderr","time":"2016-03-22T08:28:08.011059151Z"}
{"log":"I0322 08:28:08.012256       1 main.go:90] Serving on :5001\n","stream":"stderr","time":"2016-03-22T08:28:08.012484234Z"}

**Comment by rojer** [comment]
ok, what happens when you try to "docker login" to registry?

**Comment by joey-jihua** [comment]
root@ubu89:/var/lib/docker/containers/6bd8dd574b277249691f919aceaae117803a33da6922266c4180b391a52b783e# docker login registry.example.com:5000
Username: admin
Password: 
Email: zhang.jihua5@zte.com.cn
Error response from daemon: invalid registry endpoint https://registry.example.com:5000/v0/: unable to ping registry endpoint https://registry.example.com:5000/v0/
v2 ping attempt failed with error: Get https://registry.example.com:5000/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://registry.example.com:5000/v1/_ping: tls: oversized record received with length 20527. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry registry.example.com:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/registry.example.com:5000/ca.crt
root@ubu89:/var/lib/docker/containers/6bd8dd574b277249691f919aceaae117803a33da6922266c4180b391a52b783e#

**Comment by rojer** [comment]
i asked about the auth server log.

look, i don't have time for this hand holding. read the docs, get a clue, file an issue *only* if you have a code bug to report.

**Comment by joey-jihua** [comment]
thanks a lot for your time!

**Comment by gbougeard** [comment]
Hi @rojer , I'm also trying to access the registry REST API through the browser or curl and also get 401 errors : 

```
{
errors: [
{
code: "UNAUTHORIZED",
message: "authentication required",
detail: [
{
Type: "registry",
Name: "catalog",
Action: "*"
}
]
}
]
}
```

I allowed `pull` for anonymous users and `push` to one and only one user.
I'd like to access the registry REST API (at least GET routes) without authentication. Are there other grants than `pull` `push` and `*` to achieve that?
