### ISSUE TITLE
How to get the binary file without Docker support

### ISSUE THREAD

**Issue by duyanghao** [cesanta/docker_auth#80]
I want to get the binary file,running directly in physical machine without Docker support.But there is nothing about that.urgently!!!

**Comment by rojer** [comment]
download the docker container, extract docker_auth binary from it.

**Comment by duyanghao** [comment]
Sorry,What I mean is to produce binary file from compiling source code.Is there detailed steps for that?

**Comment by carsonoid** [comment]
You could just use the export
<https://docs.docker.com/engine/reference/commandline/export/>command:

docker create --name auth_server cesanta/docker_auth
docker export auth_server |tar -xv auth_server
docker rm auth_server

Tada!
