### ISSUE TITLE
Version tagged releases

### ISSUE THREAD

**Issue by dpetzel** [cesanta/docker_auth#82]
We've been using the stable tag for a bit now without issue, but it feels like we are tempting fate a bit by not pinning to a static tag. Do you think it would be possible to apply some versioned (or some other unchanging) tag on Docker Hub?

For most images that do this we'd just push a known version into our own internal registry, but since this image is needed to actually build that system we rely on Docker hub for this one.

Thanks

**Comment by rojer** [comment]
i agree, there should be proper releases. never thought it would get this far :)

**Comment by carsonoid** [comment]
In the meantime you can always export the image to an archive then put it
on a Web server and use that as the source for stability. Versioned tags
are ideal but you do have options.

**Comment by gauravbhandare** [comment]
Any update on versioned tags? As recommended we are using an archive but having a versioned tag in Docker hub will help better track versions and upgrades.

**Comment by rojer** [comment]
next release, whenever that is, will be tagged.

**Comment by rojer** [comment]
https://github.com/cesanta/docker_auth/releases/tag/1.0
