### ISSUE TITLE
X-Real-IP or X-Forwarded-For headers?

### ISSUE THREAD

**Issue by JoeOrtiz** [cesanta/docker_auth#83]
Is it possible to add to listen for the above headers? Just in case if we place docker_auth behind an nginx proxy/ELB ?

**Comment by rojer** [comment]
makes sense.
plan:
1) add server.real_ip_header, default - empty
2) if server.real_ip_header is set, retrieve it from the incoming request, remove spaces, split by commas, take the leftmost entry
3) try parsing as ipv4 first, then ipv6
4) if parsed ok, use as client ip, if not, reject request (do not use connection ip, which might be internal).

should be easy enough to do, but as always - no ETA. feel free to send a PR.
