### ISSUE TITLE
RBAC support in acls

### ISSUE THREAD

**Issue by carsonoid** [cesanta/docker_auth#84]
I've been thinking a lot about acls and access control at scale. It seems to me that needing to support RBAC is inevitable. [gorbac](https://github.com/mikespook/gorbac) is available and could be used to load in roles from Mongo, static, and ldap sources. In my mind it would work the same way as ACLs do now where we refresh them on a regular basis and hold them in memory for validation. 

Roles would go hand-in-hand with ACLs, with the ACLs functioning more as high-level rules and roles providing the more fluid and fine-grained control.

I'd be willing to code it, but I'm interested in input from others about what we would want out of role based access.

**Comment by rojer** [comment]
ok, please describe a couple cases that are not well served by the current system and how they would be better addressed by RBAC.
also, how it will fit into the current authn/authz model, or will it fully replace it?

**Comment by carsonoid** [comment]
Mainly this happens to me when I have lots of teams that need specific
access to multiple projects. I work for a company with 700+ people and this
is quickly becoming an issue.  We follow the principle of least privilege
so I need to maintain highly specific access. At it's simplest I would like
to be able to add users to groups and then simply add group access to
individual repos. Group membership could then be managed instead of
constantly changing the ACLs.  Group membership is unordered as well so
it's much easier to automate when compared to automatically adding ACLs.

Say I have a team of 10 individuals that need full access to 2 repositories
while everyone else only has pull access. Right now I would have to add
either a ton of individual ACLs, a huge regex expression, or have them all
log in as a the same user which has access to that project.  And when
anyone leaves/joins the team the maintenance is a nightmare. Whereas if I
could just put the users in a group and give the group access it suddenly
becomes much more manageable. Moreover, groups could easily fit into the
current authz model. ACLs would simply need an added field for group along
with account and name.  We might even do group resolution ourselves and
skip gorbac.

There will be extra work required in authz to fetch groups for the
requesting user each time a authz request comes in, but we could find ways
to mitigate that. Maybe by allowing group support to be disabled or by
caching user data for a period of time.

**Comment by rojer** [comment]
ok, that makes sense. someone also asked for LDAP-based group auth, which makes sense, groups are a first-class citizen in ldap.

we could implement group authz as just another authz, right? so no major API changes.
my guess would be that that for your own use you'd like group storage to be in mongo.
now, the question is - should we implement group authz with swappable backends (mongo, ldap, perhaps sql) or just implement them separately - mongo_group_authz, ldap_group_authz, etc.
wdyt?

**Comment by hsluoyz** [comment]
Hi, I'm the author of [casbin](https://github.com/hsluoyz/casbin). It is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database.

AFAIK, gorbac doesn't support 2. and 3. in RBAC, nor other models like ABAC. So basically casbin is more powerful. Please consider it and let me know if there's any question:)

**Comment by carsonoid** [comment]
I think that this is solved by the addition of labels. I'm working on a PR to add label support into the Mongo integration. Once that is merged this can be closed.

**Comment by carsonoid** [comment]
@rojer this can be closed once #194 and #195  are approved and merged.
