### ISSUE TITLE
What is the exact protocol between docker engine and auth server?

### ISSUE THREAD

**Issue by duyanghao** [cesanta/docker_auth#85]
What is the exact protocol between the docker engine and auth server?Is the HTTP or HTTPS?
As  the .yml file describes below:
```
#  auth:
#    token:
#      realm: "https://127.0.0.1:5001/auth"
#      service: "Docker registry"
#      issuer: "Acme auth server"
#      rootcertbundle: "/path/to/server.pem"

```
From the **realm: "https://127.0.0.1:5001/auth"** ,I know it is using HTTPS protocol!
But the question is that:
**Now that we are using HTTPS protocol,where is the certificate and key on the side of auth server,and where is root certificate on the side of docker engine?**

**Comment by rojer** [comment]
registry does not actually talk directly to the server. it sends the user to a particular server to obtain a token, which the user then sends to the registry. registry will verify it using the specified root bundle.
https connections are between the user and the auth server.
for more details, read the protocol spec [here](https://github.com/docker/distribution/blob/master/docs/spec/auth/token.md)

**Comment by duyanghao** [comment]
Yes,I do know that  https connections are between the user and the auth server.So my question is where is the certificate and key on the side of auth server,and where is root certificate on the side of docker client? 
you may not get my point! @rojer

**Comment by rojer** [comment]
cert and key on the auth server side are configured in, `server.certificate` and `server.key`. funny, i know. whoddathunk.

docker client uses system root ca store to verify.

**Comment by duyanghao** [comment]
As you said above,if auth server uses a self signed certificate, and docker client uses system root ca to verify, the result on the side of docker will be refused!
But my test shows the actual result is successful! I can normally use the docker,auth server and Registry v2!

**Comment by rojer** [comment]
i would hope that docker client does use cert verification when connecting, but have not actually tested it.
if you are working in an organization, it could also be that you have an org-wide CA installed on the workstations.
you can test SSL/TLS with e.g. `curl -v` or `openssl s_client` and check what cert is presented and if it is verified by your client.

**Comment by duyanghao** [comment]
thanks @rojer , My test shows that the docker client verify only in some situation.
If i use HTTPS protocol between the docker client and Registry v2, then docker client will verify!
If i use HTTP protocol between the docker client and Registry v2,then docker client will not verify!

**Comment by rojer** [comment]
there is nothing ti verify in the case of plain HTTP, so this is WAI.

**Comment by duyanghao** [comment]
@rojer I mean use HTTP

**Comment by rojer** [comment]
i'm not sure, but never mind.
i use https everywhere and everyone else should too.

**Comment by duyanghao** [comment]
Anyway,thankyou! @rojer

**Comment by duyanghao** [comment]
Anyway,thankyou! @rojer
