### ISSUE TITLE
When using mongodb authentication and authorization , why take some time to take effect？

### ISSUE THREAD

**Issue by ybshen** [cesanta/docker_auth#86]
I set cache_ttl to a little value , still do not take effect

**Comment by carsonoid** [comment]
Can you post your config?

**Comment by rojer** [comment]
also, run the server with `--v=2` - are there messages about refreshing cache?
you can post the log here, we'll take a look

**Comment by ybshen** [comment]
The following is my config:
when  i add this acl into mongodb,then i push a image into test/mariadb repository,but first push is failed,the prompt is unauthorized: authentication required.A moment later，i push the image successfully.
1、Is not because there is no synchronization to complete the authorization information?
2、What should I do when I add a acl record to take effect immediately?
3、I want to take effect immediately, what cache_ttl'value should be taken?
thanks


server:  # Server settings.
  # Address to listen on.
  addr: ":5001"
  # TLS certificate and key.
  certificate: "/ssl/domain.crt"
  key: "/ssl/domain.key"

token:  # Settings for the tokens.
  issuer: "Acme auth server"  # Must match issuer in the Registry config.
  expiration: 900
mongo_auth:
  # Essentially all options are described here: https://godoc.org/gopkg.in/mgo.v
2#DialInfo
  dial_info:
    # The MongoDB hostnames or IPs to connect to.
    addrs: ["10.70.197.178"]
    # The time to wait for a server to respond when first connecting and on
    # follow up operations in the session. If timeout is zero, the call may
    # block forever waiting for a connection to be established.
    # (See https://golang.org/pkg/time/#ParseDuration for a format description.)

    timeout: "10s"
    # Database name that will be used on the MongoDB server.
    database: "docker_auth"
    # The username with which to connect to the MongoDB server.
    user: ""
    # Path to the text file with the password in it.
    password_file: ""
  # Name of the collection in which ACLs will be stored in MongoDB.
  collection: "users"
  # Unlike acl_mongo we don't cache the full user set. We just query mongo for
  # an exact match for each authorization
acl_mongo:
  # Essentially all options are described here: https://godoc.org/gopkg.in/mgo.v
2#DialInfo
  dial_info:
    # The MongoDB hostnames or IPs to connect to.
    addrs: ["10.70.197.178"]
    # The time to wait for a server to respond when first connecting and on
    # follow up operations in the session. If timeout is zero, the call may
    # block forever waiting for a connection to be established.
    # (See https://golang.org/pkg/time/#ParseDuration for a format description.)

    timeout: "10s"
    # Database name that will be used on the MongoDB server.
    database: "docker_auth"
    # The username with which to connect to the MongoDB server.
    user: ""
    # Path to the text file with the password in it.
    password_file: ""
  # Name of the collection in which ACLs will be stored in MongoDB.
  collection: "acl"
  # Specify how long an ACL remains valid before they will be fetched again from

  # the MongoDB server.
  # (See https://golang.org/pkg/time/#ParseDuration for a format description.)
  cache_ttl: "0.01m"

**Comment by ybshen** [comment]
i set cache_ttl to 1s,acl refresh logs is printed.but when i push a image to authorized's repository,"authentication required" is still appear.after I repushed some times, it is successfully

**Comment by ybshen** [comment]
I found when i push a image to one repository,a pull another repository image lary had been execed

**Comment by rojer** [comment]
this makes zero sense to me. post a log at v=2. please.

**Comment by ybshen** [comment]
1:43180 [{repository test2/php [pull push]} {repository ubuntu/tomcat [pull]}]}
I0401 08:59:58.299993       1 mongo_auth.go:90] Checking user test2 against Mong
o Users. DB: docker_auth, collection:users
I0401 08:59:58.428349       1 server.go:168] Authn MongoDB test2 -> true, %!s(<n
il>)
I0401 08:59:58.428721       1 acl.go:97] {test2 pull,push repository test2/php}
matched {"Match":{"account":"/.+/","name":"${account}/*"},"Actions":["*"],"Comme
nt":"All logged in users can push all images that are in a namespace beginning w
ith their name"} (Comment: %!s(*string=0xc82023c9a0))
I0401 08:59:58.429036       1 server.go:187] Authz MongoDB ACL {test2 pull,push
repository test2/php} -> [pull push], %!s(<nil>)
I0401 08:59:58.429664       1 server.go:187] Authz MongoDB ACL {test2 pull repos
itory ubuntu/tomcat} -> [], did not match any rule
W0401 08:59:58.429744       1 server.go:199] {test2 pull repository ubuntu/tomca
t} did not match any authz rule
I0401 08:59:58.502036       1 server.go:276] New token for {test2:***@172.16.94.
1:43180 [{repository test2/php [pull push]} {repository ubuntu/tomcat [pull]}]}:
 {"iss":"Acme auth server","sub":"test2","aud":"Acme auth server","exp":14595020
98,"nbf":1459501197,"iat":1459501198,"jti":"8407575092190921785","access":[{"typ
e":"repository","name":"test2/php","actions":["pull","push"]},{"type":"repositor
y","name":"ubuntu/tomcat","actions":[]}]}
I0401 08:59:58.609651       1 server.go:312] Auth request: {test2:***@172.16.94.
1:43183 [{repository test2/php [pull push]} {repository ubuntu/tomcat [pull]} {r
epository zstest/php [pull]}]}
I0401 08:59:58.609824       1 mongo_auth.go:90] Checking user test2 against Mong
o Users. DB: docker_auth, collection:users
I0401 08:59:58.755055       1 server.go:168] Authn MongoDB test2 -> true, %!s(<n
il>)
I0401 08:59:58.755441       1 acl.go:97] {test2 pull,push repository test2/php}
matched {"Match":{"account":"/.+/","name":"${account}/*"},"Actions":["*"],"Comme
nt":"All logged in users can push all images that are in a namespace beginning w
ith their name"} (Comment: %!s(*string=0xc82023c9a0))
I0401 08:59:58.755551       1 server.go:187] Authz MongoDB ACL {test2 pull,push
repository test2/php} -> [pull push], %!s(<nil>)
I0401 08:59:58.755686       1 server.go:187] Authz MongoDB ACL {test2 pull repos
itory ubuntu/tomcat} -> [], did not match any rule
W0401 08:59:58.755714       1 server.go:199] {test2 pull repository ubuntu/tomca
t} did not match any authz rule
I0401 08:59:58.755792       1 server.go:187] Authz MongoDB ACL {test2 pull repos
itory zstest/php} -> [], did not match any rule
W0401 08:59:58.755835       1 server.go:199] {test2 pull repository zstest/php}
did not match any authz rule
I0401 08:59:58.835704       1 server.go:276] New token for {test2:***@172.16.94.
1:43183 [{repository test2/php [pull push]} {repository ubuntu/tomcat [pull]} {r
epository zstest/php [pull]}]}: {"iss":"Acme auth server","sub":"test2","aud":"A
cme auth server","exp":1459502098,"nbf":1459501197,"iat":1459501198,"jti":"92460
3798782881387","access":[{"type":"repository","name":"test2/php","actions":["pul
l","push"]},{"type":"repository","name":"ubuntu/tomcat","actions":[]},{"type":"r
epository","name":"zstest/php","actions":[]}]}

**Comment by ybshen** [comment]
Above is my log when i exec that  docker push myregistry.com:5000/test2/php

**Comment by rojer** [comment]
ok, now explain what you think is problematic here (please post as an attachment or enclose in triple backticks for better readability). what should be allowed and wasn't?

**Comment by ybshen** [comment]
I'm sorroy.I upload attachments to meet some problems.
The currently logged in user is test2.
the acl is:
{"seq": 50, "match" : {"account" : "/.+/", "name" : "${account}/*"}, "actions" :
 ["*"], "comment" : "All logged in users can push all images that are in a names
pace beginning with their name"}
when i pushed a image to the test2/php,"test2 pull repository zstest/php" and "test2 pull repository ubuntu/tomcat"  and "test2 pull repository zstest/php" have been executed.
This is what causes it ?
thanks.

**Comment by ybshen** [comment]
I solved it.thanks

**Comment by rojer** [comment]
great, thanks
