### ISSUE TITLE
how can i generate .pem / .key file for server -> certificate and server -> key in config.yml ?

### ISSUE THREAD

**Issue by redhatlinux10** [cesanta/docker_auth#90]
my question:
1, in `reference.yml` file, the certficate file has extension `.pem`, can this be a `.crt` file ?
2, i has read some in wikipedia and knows there can be public key / private key / certificate in a `.pem` file ，what does the `.pem` file mentioned in `reference.yml` contain ?
3, can you give commands based on openssl to create `.pem` / `.key` file for `reference.yml` ?
plz help.
in am using ubuntu 14.04

**Comment by rojer** [comment]
the extension does not matter. server.pem file should contain certificate in PEM format (base64-encoded DER with BEGIN CERTIFICATE / END CERTIFICATE markers), server.key should contain the corresponding private key, also in PEM format.
there are numerous tutorial on the internet on how to generate certificate and key using openssl, use one of those.
