### ISSUE TITLE
IP based ACL - always returns IP of the registry

### ISSUE THREAD

**Issue by rivaros** [cesanta/docker_auth#94]
Experimented a little with IP-based ACLs and   `real_ip_header: "X-Real-IP"` parameter from config file. Seems like IP in my case is always the IP of the docker registry, since it is registry who is quering for ACL. Cient IP is not passed. My registry & cesanta/docker_auth are running inside containers and are behind nginx proxy.

Does this make sense or I am missing some point ?

**Comment by rojer** [comment]
actually, it's the client that queries for token which it then brings back to the registry.
so you _should_ see client's IP in requests to the auth server.
can you run with `--v=3` and show me the logs?
in particular, this line should log connection ip and ip obtained from the header: https://github.com/cesanta/docker_auth/blob/master/auth_server/server/server.go#L133

**Comment by rojer** [comment]
i believe this to be invalid. please reopen if you have further evidence of incorrect IP being associated with a request.

**Comment by gbergere** [comment]
Having the same issue I don't see any solution in here. :/
