### ISSUE TITLE
Some uthorization errors

### ISSUE THREAD

**Issue by rivaros** [cesanta/docker_auth#95]
Though push/pull works fine, I am still getting the following errors in docker registry log:

```
172.18.0.1 - - [02/May/2016:15:31:03 +0000] "GET /v2/ HTTP/1.0" 401 87 "" "docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/4.4.8-boot2docker os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \\(darwin\\))"
time="2016-05-02T15:31:10Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.5.3 http.request.host=******** http.request.id=576587db-d6bf-4795-9527-ec8a89440f99 http.request.method=GET http.request.remoteaddr=178.136.121.88 http.request.uri="/v2/" http.request.useragent="docker/1.11.1 go/go1.5.4 git-commit/5604cbe kernel/4.4.8-boot2docker os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \\(darwin\\))" instance.id=193bfd18-da97-4c81-b6bb-d7d43bc97d81 version=v2.3.1
```

Looks like it tries to reach the '/v2/' location and fails. Here are my ACLs:

```
  - match: {account: "/.+/", type: "registry", name: "catalog"}
    actions: ["*"]
    comment: "Logged in users can query the catalog."
  - match: {account: "/.+/"}
    actions: ["pull"]
    comment: "Logged in users can pull all images."

```

**Comment by rojer** [comment]
access to `/v2/` does not even reach auth server.
some clients (i know python client does it) use /v2/ to "ping" the registry to check whether it's v1 or v2.
i think these errors are normal.

**Comment by KaleoCheng** [comment]
So how could I get the catalog using curl? @rojer

**Comment by houht** [comment]
You can refer to the following link:

https://github.com/lauraglasu/registry-api-calls
http://www.cakesolutions.net/teamblogs/docker-registry-api-calls-as-an-authenticated-user

1 curl -LI http://10.0.2.47:5000/v2/_catalog
2 curl -ivk -s -u admin:badmin -d "service=Docker registry" -d "scope=registry:catalog:*" -d "account=admin" https://10.0.2.47:5001/auth
3 curl -H "Authorization: Bearer $token" http://10.0.2.47:5000/v2/_catalog

**Comment by KaleoCheng** [comment]
So thanks.  It  works  now. @houht
