### ISSUE TITLE
LDAP incorrect password returns 500 error

### ISSUE THREAD

**Issue by gauravbhandare** [cesanta/docker_auth#97]
I have been using docker_auth for securing Docker Registry and is working fine with LDAP integration. One thing that I observe is when the user provides invalid credentials the check fails as expected but returns 500 Internal Server Error which seems like an unhandled exception. The docker client cannot interpret this as unauthorized and gives user an impression that something is wrong with the system rather than validating the credentials. Having a better handling for such scenarios and returning correct error codes will make sure that Docker client displays correct message.

**Comment by rojer** [comment]
i wonder why that is. can you run it with `-v 2` and paste the log here?

**Comment by gauravbhandare** [comment]
**docker_auth logs** (info masked)
{"log":"I0527 12:01:50.608788       1 server.go:312] Auth request: {user:***@nn.nn.n.n:59040 []}\n","stream":"stderr","time":"2016-05-27T16:01:50.60926941Z"}
{"log":"I0527 12:01:50.608836       1 server.go:168] Authn static user -\u003e false, did not match any rule\n","stream":"stderr","time":"2016-05-27T16:01:50.609302316Z"}
{"log":"I0527 12:01:50.608844       1 ldap_auth.go:134] Dial: starting...xxxx.xxx.xxx.com:YYY\n","stream":"stderr","time":"2016-05-27T16:01:50.609309413Z"}
{"log":"I0527 12:01:50.649566       1 ldap_auth.go:100] Bind read-only user (DN = cn=xxxx,ou=xxxx,dc=xx,dc=xx,dc=xxx,dc=com)\n","stream":"stderr","time":"2016-05-27T16:01:50.649723255Z"}
{"log":"I0527 12:01:50.679617       1 ldap_auth.go:154] search filter is (\u0026(objectClass=person)(objectClass=user)(sAMAccountName=user))\n","stream":"stderr","time":"2016-05-27T16:01:50.679881485Z"}
{"log":"I0527 12:01:50.679641       1 ldap_auth.go:164] Searching...basedDN:DC=xx,DC=xx,DC=xx,DC=xx, filter:(\u0026(objectClass=person)(objectClass=user)(sAMAccountName=user))\n","stream":"stderr","time":"2016-05-27T16:01:50.679921347Z"}
{"log":"I0527 12:01:50.766042       1 ldap_auth.go:183] Entry DN = CN=USER, OU=All Users,DC=xxx,DC=xx,DC=xx,DC=xx\n","stream":"stderr","time":"2016-05-27T16:01:50.76631039Z"}
{"log":"I0527 12:01:50.876580       1 server.go:168] Authn LDAP user -\u003e false, LDAP Result Code 49 \"Invalid Credentials\": 80090308: LdapErr: DSID-0C0903AA, comment: AcceptSecurityContext error, data 52e, v1772\u0000\n","stream":"stderr","time":"2016-05-27T16:01:50.87666174Z"}
{"log":"E0527 12:01:50.876627       1 server.go:174] {user:***@nn.nn.n.n:59040 []}: authn #2 returned error: LDAP Result Code 49 \"Invalid Credentials\": 80090308: LdapErr: DSID-0C0903AA, comment: AcceptSecurityContext error, data 52e, v1772\u0000\n","stream":"stderr","time":"2016-05-27T16:01:50.876905877Z"}


**Docker Client Logs**
docker login XXX.XXX.XXX.com
Username: user
Password:
Email: xxx.xxx@xxx.com
Error response from daemon: no successful auth challenge for https://<docker registry>/v2/ - errors: [token auth attempt for registry https://<docker registry>/v2/: https://<docker registry>/auth?account=user&service=Docker+registry request failed with status: 500 Internal Server Error]

**Comment by gauravbhandare** [comment]
Any luck?

**Comment by rojer** [comment]
i think #104 should do it.
built and pushed cesanta/docker_auth:test97, please try and let me know if it works as expected.

**Comment by rojer** [comment]
fixed by #104
