### ISSUE TITLE
error: Error talking to Google auth backend: Post https://www.googleapis.com/oauth2/v3/token: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by rivaros** [cesanta/docker_auth#98]
Getting this error for about 2 weeks already, when pressing "sign in with google" . Is it possible that google changed something in the API?

**Comment by rojer** [comment]
just performed a sign-in on my instance and it worked. this looks like docker_auth daemon cannot talk to google API - perhaps, blocked by firewall?

**Comment by rivaros** [comment]
Digging deeper into the problem (not frewall): 

https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token%20id_token&scope=openid%20profile%20email&client_id=655014632460-9qtelkeq72nh7pedhegei8lbdr73g35g.apps.googleusercontent.com&login_hint=AJDLj6IIYgtz12RnkrjH6u767COYKBTFCJGTphDJrVVD_gmWAjAUutilEkR-tKSPMxJOUd9BRbcy9mU2MgZLQqNA7u7IsFx_SOm8fqrZnHjOf26yY_P2r6A&ss_domain=https%3A%2F%2Fregistry.mydomain.com&origin=https%3A%2F%2Fregistry.mydomain.com

getting the error from Google :(

{"error":"IMMEDIATE_FAILED","detail":"Not all scopes are approved."}

**Comment by rivaros** [comment]
Thanks for the hint.

Actually the problem was with --iptables=false setting in docker config. We needed to disable access from outside to ports 5000 (registry) and 5001(docker_auth), since docker mangled with iptables itself. 
http://blog.viktorpetersson.com/post/101707677489/the-dangers-of-ufw-docker

Finally the solution was adding a simple rule
```
-A POSTROUTING -s 172.18.0.0/16 ! -o docker0 -j MASQUERADE
```
and making it persistent.

**Comment by rojer** [comment]
ok, good to know.
